INSERT INTO LocalizedText (Language, Tag, Text)
VALUES
	('en_US', 'TXT_KEY_BUILDING_ATASH', 'Atash'),
	('en_US', 'TXT_KEY_BUILDING_AUL', 'Aul'),
	('en_US', 'TXT_KEY_BUILDING_GURDWARA', 'Gurdwara'),
	('en_US', 'TXT_KEY_BUILDING_XUEMIAO', 'Xuemiao'),
	('en_US', 'TXT_KEY_BUILDING_JINJA', 'Jinja'),
	('en_US', 'TXT_KEY_BUILDING_ATASH_STRATEGY', 'Can only be built in cities following a religion with the Atash belief. Construct this building by purchasing it with [ICON_PEACE] Faith. Build the Atash to gain Faith, Culture, and once you have researched Acoustics, Tourism in the City.'),
	('en_US', 'TXT_KEY_BUILDING_AUL_STRATEGY', 'Can only be built in cities following a religion with the Aul belief. Construct this building by purchasing it with [ICON_PEACE] Faith. Build the Aul to gain Faith, Great General Points and once you have researched Theology, Tourism in the City.'),
	('en_US', 'TXT_KEY_BUILDING_GURDWARA_STRATEGY', 'Can only be built in cities following a religion with the Gurdwara belief. Construct this building by purchasing it with [ICON_PEACE] Faith. Build the Gurdwara to gain Faith, a Great Work of Art slot and reduce Boredom, Distress, Illiteracy, and Poverty.'),
	('en_US', 'TXT_KEY_BUILDING_XUEMIAO_STRATEGY', 'Can only be built in cities following a religion with the Xuemiao belief. Construct this building by purchasing it with [ICON_PEACE] Faith. Build the Xuemiao to gain faster Great People, a Great Work of Literature slot and once you expend these Great People, instant Science.'),
	('en_US', 'TXT_KEY_BUILDING_JINJA_STRATEGY', 'Can only be built in cities following a religion with the Jinja belief. Construct this building by purchasing it with [ICON_PEACE] Faith. Build the Jinja to gain Faith, a Great Work of Music slot and Great Admiral Points.'),
	('en_US', 'TXT_KEY_BUILDING_ATASH_TEXT', 'A place of worship for the religion of Zoroastrianism. Inside would find a fire along with clean water that when mixed creates purity of life. As the ashes are important in Zoroastrianism creating symbolism of life and religion.'),
	('en_US', 'TXT_KEY_BUILDING_AUL_TEXT', 'A theoretical place of worship for the religion of Tengriism. Although cave shrines have been claimed to be used as a place of worship. Tengriism followers mostly found their place of worship within nature itself.'),
	('en_US', 'TXT_KEY_BUILDING_GURDWARA_TEXT', 'A place of worship for Sikhs. People from all faiths and even without faith are welcomed in these gurdwaras where they can find a path to the Guru or all-mighty knowledge rouhgly translated. Inside may find a place of welcome and diversity where all faiths are to be respected for all faiths and without should eventually lead to the Sikh''s belief of peace and knoweldge.'),
	('en_US', 'TXT_KEY_BUILDING_XUEMIAO_TEXT', 'A place of worship for Confucianism. Sages and philosophers would find comfort in these places for it was a temple of study and learning for all that wish to endeavor.'),
	('en_US', 'TXT_KEY_BUILDING_JINJA_TEXT', 'A place of worship for Shinto. Inside these shrines were meant to hold cultural valuable objects to dedicate toward their spirits rather than be mainly used as a place of worship.'),
	('en_US', 'TXT_KEY_BUILDING_ATASH_HELP', 'Reduces [ICON_HAPPINESS_3] Boredom. Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this city by 25%, and increases the city''s resistance to conversion by 10%. 10% of this City''s [ICON_PEACE] Faith is converted into [ICON_RESEARCH] Science every turn. +3 [ICON_TOURISM] Tourism once you have researched Acoustics.'),
	('en_US', 'TXT_KEY_BUILDING_AUL_HELP', 'Reduces [ICON_HAPPINESS_3] Poverty. Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this city by 25%, and increases the city''s resistance to conversion by 10%. +1 [ICON_FOOD] Food from Camps, Plantations, and Pastures. +2 [ICON_TOURISM] Tourism once you have researched Theology.'),
	('en_US', 'TXT_KEY_BUILDING_GURDWARA_HELP', 'Reduces [ICON_HAPPINESS_3] Boredom, Distress, Illiteracy, and Povetry. Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this city by 10%.'),
	('en_US', 'TXT_KEY_BUILDING_XUEMIAO_HELP', 'Reduces [ICON_HAPPINESS_3] Illiteracy. Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this city by 25%, and increases the city''s resistance to conversion by 10%. +10 [ICON_RESEARCH] Science when a Great Person is expended.'),
	('en_US', 'TXT_KEY_BUILDING_JINJA_HELP', 'Reduces [ICON_HAPPINESS_3] Distress. Boosts Pressure of [ICON_RELIGION] Religious Majority emanating from this city by 25%, and increases the city''s resistance to conversion by 10%. +1 [ICON_PEACE] Faith from Coast and Ocean tiles.'),
	('en_US', 'TXT_KEY_BELIEF_ATASH', 'Use [ICON_PEACE] Faith to purchase Atash'),
	('en_US', 'TXT_KEY_BELIEF_AUL', 'Use [ICON_PEACE] Faith to purchase Aul'),
	('en_US', 'TXT_KEY_BELIEF_GURDWARA', 'Use [ICON_PEACE] Faith to purchase Gurdwara'),
	('en_US', 'TXT_KEY_BELIEF_XUEMIAO', 'Use [ICON_PEACE] Faith to purchase Xuemiao'),
	('en_US', 'TXT_KEY_BELIEF_JINJA', 'Use [ICON_PEACE] Faith to purchase Jinja'),
	('en_US', 'TXT_KEY_BELIEF_ATASH_SHORT', 'Atash'),
	('en_US', 'TXT_KEY_BELIEF_AUL_SHORT', 'Aul'),
	('en_US', 'TXT_KEY_BELIEF_GURDWARA_SHORT', 'Gurdwara'),
	('en_US', 'TXT_KEY_BELIEF_XUEMIAO_SHORT', 'Xuemiao'),
	('en_US', 'TXT_KEY_BELIEF_JINJA_SHORT', 'Jinja'),
	('en_US', 'TXT_KEY_BUILDING_ATASH_TOOLTIP', '+2 [ICON_PEACE] Faith[NEWLINE]+2 [ICON_CULTURE] Culture[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_ATASH_HELP}'),
	('en_US', 'TXT_KEY_BUILDING_AUL_TOOLTIP', '+3 [ICON_PEACE] Faith[NEWLINE]+2 [ICON_GREAT_GENERAL] Great General Points[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_AUL_HELP}'),
	('en_US', 'TXT_KEY_BUILDING_GURDWARA_TOOLTIP', '+3 [ICON_PEACE] Faith[NEWLINE]1 [ICON_GREAT_WORK] Great Work of Music Slot[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_GURDWARA_HELP}'),
	('en_US', 'TXT_KEY_BUILDING_XUEMIAO_TOOLTIP', '+2 [ICON_PEACE] Faith[NEWLINE]+20% [ICON_GREAT_PEOPLE] Great Person Rate[NEWLINE]1 [ICON_GREAT_WORK] Great Work of Literature Slot[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_XUEMIAO_HELP}'),
	('en_US', 'TXT_KEY_BUILDING_JINJA_TOOLTIP', '+2 [ICON_PEACE] Faith[NEWLINE]+3 [ICON_GREAT_ADMIRAL] Great Admiral Points[NEWLINE]1 [ICON_GREAT_WORK] Great Work of Art Slot[NEWLINE][NEWLINE]{TXT_KEY_BUILDING_JINJA_HELP}'),
	('en_US', 'TXT_KEY_BELIEF_FOT', 'May build Aqueducts, Grocers, Hospitals, and Medical Labs with [ICON_PEACE] Faith. These buildings produce +2 [ICON_FOOD] Food and [ICON_PRODUCTION] Production. We Love the King Day boosts the [ICON_FOOD] Food output of a city by 10%.'),
	('en_US', 'TXT_KEY_BELIEF_FOT_SHORT', 'Food for Thought');

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
SELECT 'BUILDINGCLASS_ATASH', 'BUILDING_ATASH', 'TXT_KEY_BUILDING_ATASH' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDINGCLASS_AUL', 'BUILDING_AUL', 'TXT_KEY_BUILDING_AUL' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDINGCLASS_GURDWARA', 'BUILDING_GURDWARA', 'TXT_KEY_BUILDING_GURDWARA' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDINGCLASS_XUEMIAO', 'BUILDING_XUEMIAO', 'TXT_KEY_BUILDING_XUEMIAO' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDINGCLASS_JINJA', 'BUILDING_JINJA', 'TXT_KEY_BUILDING_JINJA' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Beliefs (Type, Description, ShortDescription, Follower, Tooltip)
SELECT 'BELIEF_ATASH', 'TXT_KEY_BELIEF_ATASH', 'TXT_KEY_BELIEF_ATASH_SHORT', 1, 'TXT_KEY_BUILDING_ATASH_TOOLTIP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_AUL', 'TXT_KEY_BELIEF_AUL', 'TXT_KEY_BELIEF_AUL_SHORT', 1, 'TXT_KEY_BUILDING_AUL_TOOLTIP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_GURDWARA', 'TXT_KEY_BELIEF_GURDWARA', 'TXT_KEY_BELIEF_GURDWARA_SHORT', 1, 'TXT_KEY_BUILDING_GURDWARA_TOOLTIP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_XUEMIAO', 'TXT_KEY_BELIEF_XUEMIAO', 'TXT_KEY_BELIEF_XUEMIAO_SHORT', 1, 'TXT_KEY_BUILDING_XUEMIAO_TOOLTIP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_JINJA', 'TXT_KEY_BELIEF_JINJA', 'TXT_KEY_BELIEF_JINJA_SHORT', 1, 'TXT_KEY_BUILDING_JINJA_TOOLTIP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Buildings (Type, BuildingClass, Description, Civilopedia, Strategy, Help, ConquestProb, ReligiousPressureModifier, ConversionModifier, Cost, UnlockedByBelief, FaithCost, ArtDefineTag, MinAreaSize, IconAtlas, PortraitIndex)
SELECT 'BUILDING_ATASH', 'BUILDINGCLASS_ATASH', 'TXT_KEY_BUILDING_ATASH', 'TXT_KEY_BUILDING_ATASH_TEXT', 'TXT_KEY_BUILDING_ATASH_STRATEGY', 'TXT_KEY_BUILDING_ATASH_HELP', 100, 25, -10, -1, 1, 200, 'TEMPLE', -1, 'BW_ATLAS_1', 37 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_AUL', 'BUILDINGCLASS_AUL', 'TXT_KEY_BUILDING_AUL', 'TXT_KEY_BUILDING_AUL_TEXT', 'TXT_KEY_BUILDING_AUL_STRATEGY', 'TXT_KEY_BUILDING_AUL_HELP', 100, 25, -10, -1, 1, 200, 'TEMPLE', -1, 'COMMUNITY_ATLAS', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_GURDWARA', 'BUILDINGCLASS_GURDWARA', 'TXT_KEY_BUILDING_GURDWARA', 'TXT_KEY_BUILDING_GURDWARA_TEXT', 'TXT_KEY_BUILDING_GURDWARA_STRATEGY', 'TXT_KEY_BUILDING_GURDWARA_HELP', 100, 10, 0, -1, 1, 200, 'TEMPLE', -1, 'EXPANSION2_BUILDING_ATLAS', 11 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_XUEMIAO', 'BUILDINGCLASS_XUEMIAO', 'TXT_KEY_BUILDING_XUEMIAO', 'TXT_KEY_BUILDING_XUEMIAO_TEXT', 'TXT_KEY_BUILDING_XUEMIAO_STRATEGY', 'TXT_KEY_BUILDING_XUEMIAO_HELP', 100, 25, -10, -1, 1, 200, 'TEMPLE', -1, 'COMMUNITY_ATLAS', 50 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_JINJA', 'BUILDINGCLASS_JINJA', 'TXT_KEY_BUILDING_JINJA', 'TXT_KEY_BUILDING_JINJA_TEXT', 'TXT_KEY_BUILDING_JINJA_STRATEGY', 'TXT_KEY_BUILDING_JINJA_HELP', 100, 25, -10, -1, 1, 200, 'TEMPLE', -1, 'EXPANSION_BW_ATLAS_1', 9 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

UPDATE Buildings
SET UnculturedHappinessChange = -10, TechEnhancedTourism = 3, EnhancedYieldTech = 'TECH_ACOUSTICS'
WHERE Type = 'BUILDING_ATASH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

UPDATE Buildings
SET PovertyHappinessChange = -10, TechEnhancedTourism = 2, EnhancedYieldTech = 'TECH_THEOLOGY'
WHERE Type = 'BUILDING_AUL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

UPDATE Buildings
SET PovertyHappinessChange = -10, DefenseHappinessChange = -10, IlliteracyHappinessChange = -10, UnculturedHappinessChange = -10, GreatWorkSlotType = 'GREAT_WORK_SLOT_MUSIC', GreatWorkCount = 1
WHERE Type = 'BUILDING_GURDWARA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

UPDATE Buildings
SET IlliteracyHappinessChange = -10, GreatWorkSlotType = 'GREAT_WORK_SLOT_LITERATURE', GreatWorkCount = 1, GreatPeopleRateModifier = 20
WHERE Type = 'BUILDING_XUEMIAO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

UPDATE Buildings
SET DefenseHappinessChange = -10, GreatWorkSlotType = 'GREAT_WORK_SLOT_ART_ARTIFACT', GreatWorkCount = 1
WHERE Type = 'BUILDING_JINJA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

INSERT INTO Building_YieldFromGPExpend (BuildingType, YieldType, Yield)
SELECT 'BUILDING_XUEMIAO', 'YIELD_SCIENCE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Building_ScienceFromYield (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ATASH', 'YIELD_FAITH', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Building_SeaPlotYieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_JINJA', 'YIELD_FAITH', 1;

INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield)
SELECT 'BUILDING_AUL', 'IMPROVEMENT_PASTURE', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_AUL', 'IMPROVEMENT_PLANTATION', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_AUL', 'IMPROVEMENT_CAMP', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ATASH', 'YIELD_FAITH', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_ATASH', 'YIELD_CULTURE', 2  WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1)UNION ALL
SELECT 'BUILDING_AUL', 'YIELD_FAITH', 3  WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1)UNION ALL
SELECT 'BUILDING_AUL', 'YIELD_GREAT_GENERAL_POINTS', 2  WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1)UNION ALL
SELECT 'BUILDING_GURDWARA', 'YIELD_FAITH', 3 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1)UNION ALL
SELECT 'BUILDING_XUEMIAO', 'YIELD_FAITH', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_JINJA', 'YIELD_FAITH', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_JINJA', 'YIELD_GREAT_ADMIRAL_POINTS', 3 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Belief_BuildingClassFaithPurchase (BeliefType, BuildingClassType)
SELECT 'BELIEF_ATASH', 'BUILDINGCLASS_ATASH' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_AUL', 'BUILDINGCLASS_AUL' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_GURDWARA', 'BUILDINGCLASS_GURDWARA' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_XUEMIAO', 'BUILDINGCLASS_XUEMIAO' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_JINJA', 'BUILDINGCLASS_JINJA' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_ATASH', 'FLAVOR_RELIGION', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_ATASH', 'FLAVOR_CULTURE', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_ATASH', 'FLAVOR_SCIENCE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_AUL', 'FLAVOR_RELIGION', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_AUL', 'FLAVOR_OFFENSE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_AUL', 'FLAVOR_CULTURE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_AUL', 'FLAVOR_TILE_IMPROVEMENT', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_AUL', 'FLAVOR_GROWTH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_GURDWARA', 'FLAVOR_RELIGION', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_GURDWARA', 'FLAVOR_HAPPINESS', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_XUEMIAO', 'FLAVOR_RELIGION', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_XUEMIAO', 'FLAVOR_GREAT_PEOPLE', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_XUEMIAO', 'FLAVOR_SCIENCE', 3 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_JINJA', 'FLAVOR_RELIGION', 6 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BUILDING_JINJA', 'FLAVOR_NAVAL_TILE_IMPROVEMENT', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Beliefs (Type, Description, ShortDescription, Reformation, Tooltip)
SELECT 'BELIEF_FOT', 'TXT_KEY_BELIEF_FOT', 'TXT_KEY_BELIEF_FOT_SHORT', 1, 'TXT_KEY_BELIEF_FOT' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Belief_YieldFromWLTKD (BeliefType, YieldType, Yield)
SELECT 'BELIEF_FOT', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 200
WHERE BuildingClass = 'BUILDINGCLASS_AQUEDUCT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1 );

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 350
WHERE BuildingClass = 'BUILDINGCLASS_GROCER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1 );

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 400
WHERE BuildingClass = 'BUILDINGCLASS_HOSPITAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1 );

UPDATE Buildings
SET UnlockedByBelief = 1, FaithCost = 550
WHERE BuildingClass = 'BUILDINGCLASS_MEDICAL_LAB' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1 );

INSERT INTO Belief_BuildingClassYieldChanges (BeliefType, BuildingClassType, YieldType, YieldChange)
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_AQUEDUCT', 'YIELD_FOOD', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_GROCER', 'YIELD_FOOD', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_HOSPITAL', 'YIELD_FOOD', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_MEDICAL_LAB', 'YIELD_FOOD', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_AQUEDUCT', 'YIELD_PRODUCTION', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_GROCER', 'YIELD_PRODUCTION', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_HOSPITAL', 'YIELD_PRODUCTION', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_MEDICAL_LAB', 'YIELD_PRODUCTION', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);

INSERT INTO Belief_BuildingClassFaithPurchase (BeliefType, BuildingClassType)
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_AQUEDUCT' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_GROCER' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_HOSPITAL' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1) UNION ALL
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_MEDICAL_LAB' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MORERELIGION' AND Value= 1);