INSERT INTO Policy_BuildingClassHappiness (PolicyType, BuildingClassType, Happiness)
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_AIR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_ELECTRIC_CO', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_BANK', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_CENTRAL_STATION', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_WAR_ACADEMY', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'POLICY_LEGALISM', 'BUILDINGCLASS_FA_SEA_ACADEMY', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_RECON' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARCHER' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MOUNTED' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_MELEE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_SIEGE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_GUN' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'PROMOTION_GENERAL_STACKING', 'UNITCOMBAT_ARMOR' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

INSERT INTO Building_GlobalYieldModifiers (BuildingType, YieldType, Yield)
SELECT 'BUILDING_FA_CENTRAL_BANK', 'YIELD_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

INSERT INTO Building_YieldFromVictory (BuildingType, YieldType, Yield)
SELECT 'BUILDING_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'BUILDING_FA_SEA_ACADEMY', 'YIELD_GREAT_ADMIRAL_POINTS', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_FA_WAR_ACADEMY', 'YIELD_GREAT_GENERAL_POINTS', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1) UNION ALL
SELECT 'BUILDING_FA_SEA_ACADEMY', 'YIELD_GREAT_ADMIRAL_POINTS', 4 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_Flavors
SET Flavor = 0
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND FlavorType = 'FLAVOR_HAPPINESS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_BuildingClassHappiness
SET Happiness = 0
WHERE BuildingClassType = 'BUILDINGCLASS_FA_ELECTRIC_POWER' AND BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_PrereqBuildingClasses
SET NumBuildingNeeded = 1
WHERE BuildingType = 'BUILDING_FA_CENTRAL_BANK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_PrereqBuildingClasses
SET NumBuildingNeeded = 1
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_PrereqBuildingClasses
SET NumBuildingNeeded = 1
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_BANK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BRAZILWOOD_CAMP' AND Value= 1 );

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BRAZILWOOD_CAMP' AND Value= 1 );

DELETE FROM Building_PrereqBuildingClasses
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BRAZILWOOD_CAMP' AND Value= 1 );

UPDATE Building_ClassesNeededInCity
SET BuildingClassType = 'BUILDINGCLASS_HARBOR'
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_FA_WAR_ACADEMY' AND YieldType = 'YIELD_FOOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET NumCityCostMod = 10, NationalPopRequired = 45, FreePromotion = 'PROMOTION_GENERAL_STACKING', GreatGeneralRateModifier = 0
WHERE Type = 'BUILDING_FA_WAR_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET NumCityCostMod = 10, NationalPopRequired = 45, FreePromotion = 'PROMOTION_FA_SEA_ACADEMY', TrainedFreePromotion = NULL
WHERE Type = 'BUILDING_FA_SEA_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET NumCityCostMod = 10, NationalPopRequired = 55, FreePromotion = 'PROMOTION_EVASION', TrainedFreePromotion = NULL
WHERE Type = 'BUILDING_FA_AIR_ACADEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET NumCityCostMod = 10, NationalPopRequired = 50
WHERE Type = 'BUILDING_FA_CENTRAL_BANK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET NumCityCostMod = 10, NationalPopRequired = 50, CityConnectionTradeRouteModifier = 50
WHERE Type = 'BUILDING_FA_CENTRAL_STATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Buildings
SET NumCityCostMod = 10, NationalPopRequired = 60, FreeBuilding = 'BUILDINGCLASS_FA_ELECTRIC_POWER'
WHERE Type = 'BUILDING_FA_ELECTRIC_CO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+10% [ICON_GOLD] Gold in all Cities. [NEWLINE][NEWLINE]The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_BANK_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+50% [ICON_GOLD] Gold from [ICON_TRADE] City Connections.[NEWLINE][NEWLINE]The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+50% [ICON_GOLD] Gold from [ICON_TRADE] City Connections.[NEWLINE][NEWLINE]The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_CENTRAL_STATION2_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'All cities receive Electric Power. Electric Power increases [ICON_RESEARCH] Science, [ICON_GOLD] Gold and [ICON_PRODUCTION] Production in its city. [NEWLINE]Must be built in a city on a river. Requires a Factory.[NEWLINE][NEWLINE]The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Electric Power increases [ICON_RESEARCH] Science, [ICON_GOLD] Gold and [ICON_PRODUCTION] Production in its city.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_ELECTRIC_CO2_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Whenever you defeat a Land Unit, 1 [ICON_GREAT_GENERAL] Great General Points. Free Arsenal in this city. +15 [ICON_WAR] XP and +15% [ICON_PRODUCTION] Production for all Land Units trained in this City. All land units may receive the Great General Combat Bonus promotion. [NEWLINE][NEWLINE]The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_WAR_ACADEMY_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Whenever you defeat a Naval Unit, 1 [ICON_GREAT_ADMIRAL] Great Admiral Points. +15 [ICON_WAR] XP and +15% [ICON_PRODUCTION] Production for all Sea Units trained in this City. All naval units may receive the Seamanship Promotion.[NEWLINE][NEWLINE]Must have a Harbor in the city. The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_SEA_ACADEMY_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+25% [ICON_PRODUCTION] Production for all Air Units. Grants the Evasion Promotion to every eligible air unit. [NEWLINE][NEWLINE]Must have a Military Academy in the city. The [ICON_PRODUCTION] Production Cost and [ICON_CITIZEN] Population Requirements increase based on the number of cities you own.'
WHERE Tag = 'TXT_KEY_BUILDING_FA_AIR_ACADEMY_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM UnitPromotions_UnitCombats
WHERE PromotionType = 'PROMOTION_FA_SEA_ACADEMY' AND UnitCombatType = 'UNITCOMBAT_NAVAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM Building_YieldModifiers
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION' AND YieldType = 'YIELD_GOLD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_CENTRAL_STATION' AND UnitType = 'UNIT_FA_CENTRAL_STATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_ELECTRIC_CO' AND UnitType = 'UNIT_FA_ELECTRIC_CO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);

DELETE FROM Building_FreeUnits
WHERE BuildingType = 'BUILDING_FA_SEA_ACADEMY' AND UnitType = 'UNIT_GREAT_ADMIRAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_NATIONAL' AND Value= 1);