-- Created by ModBuddy on 2/27/2016 6:19:16 PM

INSERT INTO Improvements
		(Type,						Description,						Civilopedia,							Help,									ArtDefineTag,						SpecificCivRequired,	CivilizationType,		RequiresFeature,	PillageGold,	PortraitIndex,	IconAtlas)
VALUES	('IMPROVEMENT_DOLLHOUSE',	'TXT_KEY_IMPROVEMENT_DOLLHOUSE',	'TXT_KEY_IMPROVEMENT_DOLLHOUSE_PEDIA',	'TXT_KEY_IMPROVEMENT_DOLLHOUSE_HELP',	'ART_DEF_IMPROVEMENT_DOLLHOUSE',	1,						'CIVILIZATION_DOLL',	1,					10,				2,				'DOLL_ATLAS');

INSERT INTO Improvement_Yields
		(ImprovementType,			YieldType,		Yield)
VALUES	('IMPROVEMENT_DOLLHOUSE',	'YIELD_GOLD',	1);

INSERT INTO Improvement_ValidFeatures
		(ImprovementType,			FeatureType)
VALUES	('IMPROVEMENT_DOLLHOUSE',	'FEATURE_FOREST');

INSERT INTO Improvement_ResourceTypes
		(ImprovementType,			ResourceType)
VALUES	('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_OIL'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_STONE'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_SILVER'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_COAL'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_IRON'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_GOLD'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_GEMS'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_ALUMINUM'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_COPPER'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_URANIUM'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_DEER'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_FUR'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_DYE'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_TRUFFLES'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_SILK'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_CITRUS'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_SPICES'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_COCOA'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_COTTON'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_INCENSE'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_WINE'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_SALT'),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_MARBLE');

INSERT INTO Improvement_ResourceType_Yields
		(ImprovementType,			ResourceType,			YieldType,			Yield)
VALUES	('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_OIL',			'YIELD_PRODUCTION',	3),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_STONE',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_SILVER',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_COAL',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_IRON',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_GOLD',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_GEMS',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_ALUMINUM',	'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_COPPER',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_URANIUM',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_DEER',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_FUR',			'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_DYE',			'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_TRUFFLES',	'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_SILK',		'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_CITRUS',		'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_SPICES',		'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_COCOA',		'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_COTTON',		'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_INCENSE',		'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_WINE',		'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_SALT',		'YIELD_FOOD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_SALT',		'YIELD_GOLD',		1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_MARBLE',		'YIELD_PRODUCTION',	1),
		('IMPROVEMENT_DOLLHOUSE',	'RESOURCE_MARBLE',		'YIELD_GOLD',		1);

INSERT INTO Improvement_TechYieldChanges
		(ImprovementType,			TechType,				YieldType,			Yield)
VALUES	('IMPROVEMENT_DOLLHOUSE',	'TECH_INDUSTRIALIZATION',	'YIELD_PRODUCTION',	1);

INSERT INTO Builds
		(Type,				Time,	ImprovementType,			Description,				Recommendation,					EntityEvent,			HotKey,	OrderPriority,	IconIndex,	IconAtlas)
VALUES	('BUILD_DOLLHOUSE',	800,	'IMPROVEMENT_DOLLHOUSE',	'TXT_KEY_BUILD_DOLLHOUSE',	'TXT_KEY_BUILD_DOLLHOUSE_REC',	'ENTITY_EVENT_BUILD',	'KB_D',	99,				28,			'UNIT_ACTION_ATLAS');

INSERT INTO Unit_Builds
		(UnitType,		BuildType)
VALUES	('UNIT_WORKER',	'BUILD_DOLLHOUSE');