-- Created by ModBuddy on 2/27/2016 6:45:42 PM

INSERT INTO Policies
		(Type,						Description,						Civilopedia,							Help)
VALUES	('POLICY_DOLL',				'TXT_KEY_POLICY_DOLL',				'TXT_KEY_POLICY_DOLL_PEDIA',			'TXT_KEY_POLICY_DOLL_HELP'),
		('POLICY_DOLL_MACHINERY',	'TXT_KEY_POLICY_DOLL_MACHINERY',	'TXT_KEY_POLICY_DOLL_MACHINERY_PEDIA',	'TXT_KEY_POLICY_DOLL_MACHINERY_HELP'),
		('POLICY_NONDOLL',			'TXT_KEY_POLICY_NONDOLL',			'TXT_KEY_POLICY_NONDOLL_PEDIA',			'TXT_KEY_POLICY_NONDOLL_HELP');

INSERT INTO Policy_ImprovementYieldChanges
		(PolicyType,				ImprovementType,			YieldType,			Yield)
VALUES	('POLICY_DOLL',				'IMPROVEMENT_DOLLHOUSE',	'YIELD_FOOD',		1),
		('POLICY_DOLL',				'IMPROVEMENT_DOLLHOUSE',	'YIELD_GOLD',		-1),
		('POLICY_DOLL',				'IMPROVEMENT_LUMBERMILL',	'YIELD_GOLD',		1),
		('POLICY_DOLL_MACHINERY',	'IMPROVEMENT_DOLLHOUSE',	'YIELD_CULTURE',	1),
		('POLICY_DOLL_MACHINERY',	'IMPROVEMENT_DOLLHOUSE',	'YIELD_FOOD',		1),
		('POLICY_DOLL_MACHINERY',	'IMPROVEMENT_LUMBERMILL',	'YIELD_PRODUCTION',	1),
		('POLICY_NONDOLL',			'IMPROVEMENT_DOLLHOUSE',	'YIELD_GOLD',		3);