INSERT INTO Language_en_US (Text, Tag)
SELECT  'No thanks. I don''t want to change now.',
		'TXT_KEY_EVENT_CIVIC_NOPE' UNION ALL
SELECT  'The old ways are best.[NEWLINE][NEWLINE]Don''t use this option more than twice in the same turn!',
		'TXT_KEY_EVENT_CIVIC_NOPE_HELP' UNION ALL		
SELECT  'Government Civics',
		'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_DESCRIPTION' UNION ALL
SELECT  '"We admit of no government by divine right ... the only legitimate right to govern is an express grant of power from the governed."[NEWLINE]--William Henry Harrison', 
		'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_HELP' UNION ALL
SELECT 	'Despotism',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-15% [ICON_HAPPINESS_3] from Illiteracy[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] Resistance: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 0%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Hereditary Rule',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Military Theory
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold and [ICON_PRODUCTION] Production from Garrison[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+5% [ICON_PRODUCTION] Production toward Wonders[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE] [NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Confederation', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Writing
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+4 [ICON_HAPPINESS_1] Happiness in the [ICON_CAPITAL] Capital[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+30% [ICON_GOLD] Gold in Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+15% [ICON_HAPPINESS_3] Unhappiness Modifier for all Needs
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[NEWLINE][ICON_BULLET]Requires Writing
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+4 [ICON_HAPPINESS_1] Happiness in the [ICON_CAPITAL] Capital[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+30% [ICON_GOLD] Gold in Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Cities generate 3 [ICON_HAPPINESS_3] Unhappiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Patronage', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Education
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]City-State [ICON_INFLUENCE] Resting Point increased by 15[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]City-State [ICON_INFLUENCE] Influence degrade -25% slower[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold to [ICON_DIPLOMAT] Civil Servants[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold in every City for every City-State Friend[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_TOURISM] Tourism in every City for every City-State Ally[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'Representation', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Printing Press
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities produce +10% [ICON_TOURISM] Tourism and [ICON_PEACE] Faith during Golden Ages[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_TOURISM] Tourism to [ICON_GREAT_ARTIST] Artists, [ICON_GREAT_MUSICIAN] Musicians, and [ICON_GREAT_WRITER] Writers[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold to [ICON_GREAT_MERCHANT] Merchant, [ICON_GREAT_ENGINEER] Engineers, and [ICON_GREAT_SCIENTIST] Scientists[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food to [ICON_DIPLOMAT] Civil Servants[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT  '[ICON_BULLET]Requires Printing Press
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_TOURISM] Tourism to [ICON_GREAT_ARTIST] Artists, [ICON_GREAT_MUSICIAN] Musicians, and [ICON_GREAT_WRITER] Writers[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold to [ICON_GREAT_MERCHANT] Merchant, [ICON_GREAT_ENGINEER] Engineers, and [ICON_GREAT_SCIENTIST] Scientists[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4_HELP' WHERE NOT EXISTS (SELECT * FROM CSD WHERE Type='CSD_DIFFICULTY') UNION ALL
SELECT  'Totalitarianism', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Rifling
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_GENERAL][ICON_GREAT_ADMIRAL] Great General/Admiral''s Combat Bonus increased by +15%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+15% Military Unit Production[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-10% [ICON_HAPPINESS_3] from War Weariness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY] Foreign Spies are +33% ineffective at stealing [ICON_RESEARCH] Technologies and [ICON_GREAT_WORK] Great Works from your Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold from Barracks, Armories, and Military Academies[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness from Police Station[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Rifling
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_GENERAL] Great General''s Combat Bonus increased by +15%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+15% Military Unit Production[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY] Foreign Spies are +33% ineffective at stealing [ICON_RESEARCH] Technologies from your Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold from Barracks, Armories, and Military Academies[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness from Police Station[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'National Suffrage', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Atomic Theory
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_TOURISM] Tourism bonus from Historic Events increased by 10%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Citizens generate +0.33 [ICON_FOOD] Food, [ICON_PRODUCTION] Production and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] Great People Improvements generates +4 [ICON_FOOD] Food[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cost of [ICON_INVEST] Gold Investments in all cities reduced by -8%[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Atomic Theory
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Citizens generate +0.33 [ICON_FOOD] Food [ICON_PRODUCTION] Production, and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] Great People Improvements generates +4 [ICON_FOOD] Food[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cost of [ICON_INVEST] Gold Investments in all cities reduced by -8%[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Legal Civics',
		'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_DESCRIPTION' UNION ALL
SELECT  '"Whoever desires to found a state and give it laws, must start with assuming that all men are bad and ever ready to display their vicious nature, whenever they may find occasion for it."[NEWLINE]--Niccolo Machiavelli', 
		'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_HELP' UNION ALL
SELECT 	'Anarchism',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-15% [ICON_HAPPINESS_3] from Distress[ENDCOLOR]
[NEWLINE][ICON_BULLET]No [ICON_RESISTANCE] Resistance when chosen
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance} [ICON_GOLD])
[NEWLINE][ICON_BULLET]No [ICON_RESISTANCE] Resistance when chosen
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Codified Law',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Mathematics
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities generate +5% [ICON_FOOD] Food during [ICON_HAPPINESS_1] "We Love The King Day!"[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities generate +5% [ICON_FOOD] Food during [ICON_GOLDEN_AGE] Golden Ages[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]A [ICON_CITIZEN] Specialist in each of your cities does not generate [ICON_HAPPINESS_3] Unhappiness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Receive 3 Gold and 1 [ICON_GOLDEN_AGE] Golden Age Points when your borders expand, scaling with era[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Feudalism', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Chivalry
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Units trained gain an additional +15 XP[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Yields from City-State increased by 20%[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Vassals tribute an additional 20% of their yields[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Military gifts to [ICON_CITY_STATE] City-States yield an additional +10 [ICON_INFLUENCE] Influence[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-30% Base Unit Maintenance (+{2_Gold}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'Bureaucracy', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Physics
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_PRODUCTION] Production and [ICON_GOLD] Gold for every [ICON_CITIZEN] Citizen in the [ICON_CAPITAL] Capital[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+100% Base Yields of the Palace and all Base National Wonders[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Palace and all Base National Wonders receives Yield Modifiers derived from their Base Yields[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]15 [ICON_CITIZEN] Specialists in your [ICON_CAPITAL] Capital do not generate [ICON_HAPPINESS_3] Unhappiness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+3 [ICON_GOLD] Gold from Courthouses[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4_HELP' UNION ALL
SELECT  'Nationhood', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Military Science
[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Gain 200 [ICON_GOLD] Gold and [ICON_GOLDEN_AGE] Golden Age Points when an Enemy [ICON_SPY] Spy is killed, scaling with era and spy level[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY] Spies are +33% more likely to capture enemy [ICON_SPY] Spies[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY] Spies steal [ICON_RESEARCH] Technologies and [ICON_GREAT_WORK] Great Works +33% faster[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY] Spies are +17% more likely to rig elections in [ICON_CITY_STATE] City-States[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Military Science[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY] Spies are +33% more likely to capture enemy [ICON_SPY]Spies[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_SPY]Spies steal [ICON_RESEARCH] Technologies +33% faster[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Spies are +17% more likely to rig elections in [ICON_CITY_STATE] City-States[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]',
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Free Speech', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Radio
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][COLOR_POSITIVE_TEXT][ICON_BULLET]+10% [ICON_CULTURE] Culture in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_PEOPLE] Great People Improvements generates +2 [ICON_CULTURE] Culture[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_GREAT_WORK] Great Works produce +2 [ICON_CULTURE] Culture and +5 [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  'Constitutionalism', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Telecommunications
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+20% [ICON_GOLDEN_AGE] Golden Age Length[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Citizens generate +1 [ICON_GOLDEN_AGE] Golden Age Point[ENDCOLOR]
[NEWLINE][COLOR_POSITIVE_TEXT][ICON_BULLET]Cities produce +10% [ICON_GOLD] Gold during a [ICON_GOLDEN_AGE] Golden Age[ENDCOLOR]
[NEWLINE][COLOR_POSITIVE_TEXT][ICON_BULLET]+25% [ICON_GREAT_PEOPLE] Great People Generation during a [ICON_GOLDEN_AGE] Golden Age[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Labor Civics',
		'TXT_KEY_PLAYER_EVENT_LABORCIVIC_DESCRIPTION' UNION ALL
SELECT  '"The night is far spent, the day is at hand; let us therefore cast off the works of darkness, and let us put on the armor of light."[NEWLINE]--The Holy Bible: Romans, 13:12', 
		'TXT_KEY_PLAYER_EVENT_LABORCIVIC_HELP' UNION ALL
SELECT 	'Tribalism',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-15% [ICON_HAPPINESS_3] from Boredom[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Slavery',
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Bronze Working
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_PRODUCTION] Production in your [ICON_CAPITAL] Capital for every 15 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_PRODUCTION] Production to Laborers, Mines, and Quarries[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Newly-founded and Conquered Cities receive a 25 [ICON_PRODUCTION] Production bonus scaling with era[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_PUPPET] Puppeted Cities and [ICON_OCCUPIED] Cities with Courthouses produce +20% more [ICON_PRODUCTION] Production[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Manorialism', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Civil Service
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food in your [ICON_CAPITAL] Capital for every 10 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Workers construct Improvements +20% faster[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Farms produce +1 [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Villages produce +1 [ICON_PRODUCTION] Production[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'Caste System', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Guilds
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GREAT_GENERAL] Great General Point and [ICON_GREAT_ADMIRAL] Great Admiral Point in your [ICON_CAPITAL] Capital for every 20 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Specialists produce an additional +1 of its base yield (Exception: Civil Servants produce +1 [ICON_CULTURE])[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+5% [ICON_HAPPINESS_3] Unhappiness Modifier for all Needs
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Guilds
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GREAT_GENERAL] Great General Point and [ICON_GREAT_ADMIRAL] Great Admiral Point in your [ICON_CAPITAL] Capital for every 20 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Specialists produce an additional +1 of its base yield[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Cities produce 1 more [ICON_HAPPINESS_3] Unhappiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Industrial Servitude', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Industrialization
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold in your [ICON_CAPITAL] Capital for every 8 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+15% [ICON_FOOD] Growth in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% [ICON_PRODUCTION] Production and [ICON_GOLD] Gold to Factories[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_RES_HORSE] Horse, [ICON_RES_IRON] Iron, [ICON_RES_COAL] Coal, [ICON_RES_ALUMINUM] Aluminum, [ICON_RES_OIL] Oil and [ICON_RES_URANIUM] Uranium produce +2 [ICON_PRODUCTION] Production and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  'Unionism', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Electricity
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLDEN_AGE] Golden Age Point and [ICON_RESEARCH] Science in your [ICON_CAPITAL] Capital for every 10 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Guilds, Labor Associations, Credit Unions, Science Institutions, and Civil Departments produce +2 of their respective yields and +1 [ICON_HAPPINESS_1] Happiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Emancipation', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Globalization
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_TOURISM] Tourism in your [ICON_CAPITAL] Capital for every 10 [ICON_CITIZEN] Citizens in your Empire[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+17% [ICON_TOURISM] Tourism to civilizations that have less [ICON_HAPPINESS_1] Happiness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness in a City per every 7 [ICON_CITIZEN] Citizens it has[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  'Economy Civics', 
		'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_DESCRIPTION' UNION ALL
SELECT  '"Better is bread with a happy heart than wealth with vexation."[NEWLINE]--Amenemope', 
		'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_HELP' UNION ALL
SELECT 	'Bartering',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-15% [ICON_HAPPINESS_3] from Poverty[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Decentralization',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Trade
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+3 [ICON_GOLD] Gold from [ICON_INTERNATIONAL_TRADE] International Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Gain +1 [ICON_INFLUENCE] Influence (per turn) with City-States that you have a [ICON_INTERNATIONAL_TRADE] Trade Route with[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Maintenance paid on Roads and Railroads reduced by 15%[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Horseback Riding
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+3 [ICON_GOLD] Gold from [ICON_INTERNATIONAL_TRADE] International Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Gain +1 [ICON_INFLUENCE] Influence (per turn) with City-States that you have a [ICON_INTERNATIONAL_TRADE] Trade Route with[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Maintenance paid on Roads and Railroads reduced by 15%.[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0) UNION ALL
SELECT  'Commercialism',
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Currency
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_FOOD] Food and [ICON_PRODUCTION] Production from [ICON_CONNECTED] City Connections[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+33% [ICON_FOOD] Food and [ICON_PRODUCTION] Production from Internal [ICON_INTERNATIONAL_TRADE] Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+20% [ICON_GOLD] Gold from [ICON_TRADE] City Connections[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Cannot create International [ICON_INTERNATIONAL_TRADE] Trade Routes to non-Allied City-States, non-Vassalized Foreign Cities and non-Master Foreign Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2_HELP' UNION ALL
SELECT  'Free Market', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Economics
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_INTERNATIONAL_TRADE] Trade Route[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Trade Units are trained 25% faster[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_GOLD] Gold to Towns[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+10% Tourism Modifier for [ICON_INTERNATIONAL_TRADE] Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'State Property', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Scientific Theory
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Corporation
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food to Mines, Quarries, Lumbermills, Logging Camps, and Manufactories[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Corporate Headquarter produces +10% [ICON_FOOD] Food and [ICON_CULTURE] Culture [ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Corporate Offices produce +4 [ICON_FOOD] Food and [ICON_PRODUCTION] Production [ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]Corporate Franchises produce +5% [ICON_FOOD] Food and +2% [ICON_CULTURE] Culture[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Scientific Theory
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_FOOD] Food to Mine, Quarry, Lumbermill, and Manufactory[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities with a Workshop produce +10% [ICON_FOOD] Food and [ICON_PRODUCTION] Production
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Corporatism', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Corporation
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Corporation
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+5% to sum of Yield and [ICON_GOLDEN_AGE] Golden Age duration modifiers from Global Monopolies[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 to sum of Yields and [ICON_HAPPINESS_1] Happiness from Global Monopolies[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Corporate Headquarter produces +15% [ICON_GOLD] Gold and [ICON_TOURISM] Tourism[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Corporate Offices produce +5 more [ICON_PRODUCTION] Production and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Corporate Franchises produce +5 [ICON_GOLD] Gold and +2 [ICON_TOURISM] Tourism[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Industrialization
[NEWLINE][ICON_BULLET]High Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Markets and Banks produce +15% more [ICON_PRODUCTION] Production and [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Environmentalism', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Ecology
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Ironworks, Coal Refineries, and Recycling Centers produce +15% [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Corporate Franchises produce +10 [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_CULTURE] Culture and +2 [ICON_GOLD] Gold to Landmark, Forest, Jungle, and Marsh[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-3 [ICON_PRODUCTION] Production to Mines, Quarries, Lumbermills, Logging Camps, and Manufactories[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-7[ENDCOLOR]', 
		'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6_HELP' UNION ALL
SELECT  'Religion Civics', 
		'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_DESCRIPTION' UNION ALL
SELECT  '"Three things are necessary for the salvation of man: to know what he ought to believe; to know what he ought to desire; and to know what he ought to do."[NEWLINE]--St. Thomas Aquinas',
		'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_HELP' UNION ALL
SELECT 	'Paganism',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1' UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]-15% [ICON_HAPPINESS_3] from Religious Strife[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: None
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+1[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-1[ENDCOLOR]',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Ancestor Veneration', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7' UNION ALL
SELECT  '[ICON_BULLET]Requires Calendar
[NEWLINE][ICON_BULLET]Low Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_PEACE] Faith[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Unlocks the faith purchases of Altars (+1 [ICON_PEACE] Faith, +1 [ICON_CULTURE_LOCAL] Border Growth Point)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Altars generate +15% [ICON_PEACE] Faith, +1 [ICON_TOURISM] Tourism, and +1 [ICON_GOLDEN_AGE] Golden Age Point[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+2 [ICON_PEACE] Faith to Natural Wonders and +5 [ICON_PEACE] Faith to Landmarks[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 25%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7_HELP' UNION ALL
SELECT  'Organized Faith',
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2' UNION ALL
SELECT  '[ICON_BULLET]Requires Philosophy
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Founder Building
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Founder Buildings produce +3 of its respective yields and +5% of all yields[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_PRODUCTION] Production[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Temples and Holy Sites generate +3 [ICON_PRODUCTION] Production[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 )  UNION ALL
SELECT  '[ICON_BULLET]Requires Philosophy
[NEWLINE][ICON_BULLET]High Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +1 [ICON_PRODUCTION] Production and [ICON_PEACE] faith[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Temple and Holy Sites generate +3 [ICON_PRODUCTION] Production[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 5%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+3[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 )  UNION ALL
SELECT  'Theocracy', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3' UNION ALL
SELECT  '[ICON_BULLET]Requires Theology
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET]Requires a Majority Religion
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Units trained gain an additional +5 XP[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Units heal 5 additional HP per turn in non-hostile territory[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_RESEARCH] Science[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Temple and Holy Sites generate +2 [ICON_GOLD] Gold[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT][ICON_MISSIONARY] Missionaries and [ICON_PROPHET] Great Prophets of [ICON_RELIGION] Foreign Religion to your [ICON_RELIGION] Majority Religion cannot spread to your Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_HELP' UNION ALL
SELECT  'Pacifism', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4' UNION ALL
SELECT  '[ICON_BULLET]Requires Biology
[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+50% [ICON_GREAT_PEOPLE] Great People Generation[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_CULTURE] Culture[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+25% [ICON_HAPPINESS_3] from War Weariness[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+100% Base Unit Maintenance (-{1_Maintenance}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Biology
[NEWLINE][ICON_BULLET]No Upkeep
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+50% [ICON_GREAT_PEOPLE] Great People Generation Rate[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_CULTURE] Culture[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]+100% Base Unit Maintenance (-{1_Maintenance}[ICON_GOLD])[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 35%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+7[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-3[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Cult of Personality', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5' UNION ALL
SELECT  '[ICON_BULLET]Requires Flight
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]50% of [ICON_HAPPINESS_1] Happiness produced in each City is added to the City''s [ICON_CULTURE] Culture per Turn[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities following your [ICON_RELIGION] Majority Religion generate +2 [ICON_GOLDEN_AGE] Golden Age Points[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Unlocks the construction of Idols (+1 [ICON_CULTURE] Culture)[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Idols generate +2 [ICON_TOURISM] Tourism and +1 [ICON_HAPPINESS_1] Happiness[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5_HELP' UNION ALL
SELECT  'Free Religion', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6' UNION ALL
SELECT  '[ICON_BULLET]Requires Penicilin
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities produce +10% [ICON_RESEARCH] Science[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities with a majority religion also get the [ICON_RELIGION_PANTHEON] Pantheon belief bonus of the second most popular religion[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-75% Pressure in all nearby Cities without your majority [ICON_RELIGION] Religion[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-75% Pressure in [ICON_INTERNATIONAL_TRADE] Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 ) UNION ALL
SELECT  '[ICON_BULLET]Requires Penicilin
[NEWLINE][ICON_BULLET]Medium Upkeep (-{1_Maintenance}[ICON_GOLD])
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]+1 [ICON_HAPPINESS_1] Happiness in all Cities[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_POSITIVE_TEXT]Cities produce +10% [ICON_RESEARCH] Science[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-75% Pressure in all nearby Cities without your majority [ICON_RELIGION] Religion[ENDCOLOR]
[NEWLINE][ICON_BULLET][COLOR_NEGATIVE_TEXT]-75% Pressure in [ICON_INTERNATIONAL_TRADE] Trade Routes[ENDCOLOR]
[NEWLINE][ICON_BULLET]Chance of [ICON_RESISTANCE] [COLOR_NEGATIVE_TEXT]Resistance[ENDCOLOR]: 15%
[NEWLINE][NEWLINE]Diplomatic Opinion: [ICON_FLOWER] [COLOR_POSITIVE_TEXT]+5[ENDCOLOR] / [ICON_DENOUNCE] [COLOR_NEGATIVE_TEXT]-5[ENDCOLOR]', 
		'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 0 ) UNION ALL
SELECT  'Taxes',
		'TXT_KEY_TAX' UNION ALL
SELECT  'Founder Status',
		'TXT_KEY_MAINTENANCEBUILDING' UNION ALL
SELECT  'Altar',
		'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION' UNION ALL
SELECT  'Idol',
		'TXT_KEY_STATE_ATHEISM_DESCRIPTION' UNION ALL
SELECT  'Might Makes Right',
		'TXT_KEY_PROMOTION_HEREDITARYRULE' UNION ALL
SELECT  'Generate +1 [ICON_GOLD] Gold and +1 [ICON_PRODUCTION] Production when [COLOR_POSITIVE_TEXT]stationed in a City[ENDCOLOR].',
		'TXT_KEY_PROMOTION_HEREDITARYRULE_HELP' UNION ALL
SELECT  'Theocratic Warrior',
		'TXT_KEY_PROMOTION_DEUSVULT' UNION ALL
SELECT  'Heal 5 additional HP per turn in non-hostile territory.',
		'TXT_KEY_PROMOTION_DEUSVULT_HELP';

INSERT INTO Events (Type, Description, Help, EventArt, RandomChance, NumChoices, IgnoresGlobalCooldown, EventCooldown)
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC', 'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_GOVERNMENTCIVIC_HELP', 'GovernmentCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC', 'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_LEGALCIVIC_HELP', 'LegalCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC', 'TXT_KEY_PLAYER_EVENT_LABORCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_LABORCIVIC_HELP', 'LaborCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC', 'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_ECONOMYCIVIC_HELP', 'EconomyCivics.dds', -1, 7, 1, 0 UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC', 'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_DESCRIPTION', 'TXT_KEY_PLAYER_EVENT_RELIGIONCIVIC_HELP', 'ReligionCivics.dds', -1, 7, 1, 0;

INSERT INTO EventChoices (Type, Description, Help, EventDuration, PrereqTech)
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_1_HELP', 1, NULL UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_2_HELP', 1, 'TECH_ARCHERY'  UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_7_HELP', 1, 'TECH_WRITING' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3_HELP', 1, 'TECH_EDUCATION' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_4_HELP', 1, 'TECH_PRINTING_PRESS' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_5_HELP', 1, 'TECH_RIFLING' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6_HELP', 1, 'TECH_ATOMIC_THEORY' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_1_HELP', 1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_2_HELP', 1, 'TECH_MATHEMATICS'  UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_3_HELP', 1, 'TECH_CHIVALRY' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_4_HELP', 1, 'TECH_PHYSICS' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5_HELP', 1, 'TECH_MILITARY_SCIENCE' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_6_HELP', 1, 'TECH_RADIO' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7_HELP', 1, 'TECH_TELECOM' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_1_HELP', 1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_2_HELP', 1, 'TECH_BRONZE_WORKING'  UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_3_HELP', 1, 'TECH_CIVIL_SERVICE' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_4_HELP', 1, 'TECH_GUILDS' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_5_HELP', 1, 'TECH_INDUSTRIALIZATION' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_7_HELP', 1, 'TECH_ELECTRICITY' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6', 'TXT_KEY_EVENT_LABORCIVIC_CHOICE_6_HELP', 1, 'TECH_GLOBALIZATION' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_1_HELP', 1, NULL UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7_HELP', 1, 'TECH_HORSEBACK_RIDING' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_2_HELP', 1, 'TECH_CURRENCY'  UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_3_HELP', 1, 'TECH_ECONOMICS' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_4_HELP', 1, 'TECH_SCIENTIFIC_THEORY' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_5_HELP', 1, 'TECH_INDUSTRIALIZATION' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_6_HELP', 1, 'TECH_ECOLOGY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_1_HELP', 1, NULL UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_7_HELP', 1, 'TECH_CALENDAR' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_2_HELP', 1, 'TECH_PHILOSOPHY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_3_HELP', 1, 'TECH_THEOLOGY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_4_HELP', 1, 'TECH_BIOLOGY' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_5_HELP', 1, 'TECH_FLIGHT' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6', 'TXT_KEY_EVENT_RELIGIONCIVIC_CHOICE_6_HELP', 1, 'TECH_PENICILIN' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', 1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', 1, NULL UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', 1, NULL UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', 1, NULL UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_8', 'TXT_KEY_EVENT_CIVIC_NOPE', 'TXT_KEY_EVENT_CIVIC_NOPE_HELP', 1, NULL;

INSERT INTO Event_ParentEvents (EventChoiceType, EventType)
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'PLAYER_EVENT_RELIGIONCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_8', 'PLAYER_EVENT_GOVERNMENTCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LEGALCIVIC_CHOICE_8', 'PLAYER_EVENT_LEGALCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_LABORCIVIC_CHOICE_8', 'PLAYER_EVENT_LABORCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_8', 'PLAYER_EVENT_ECONOMYCIVIC' UNION ALL
SELECT  'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_8', 'PLAYER_EVENT_RELIGIONCIVIC';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_LABORCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1';

UPDATE EventChoices
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1';

UPDATE EventChoices
SET PrereqTech = 'TECH_CORPORATIONS'
WHERE Type = 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CIVICS' AND Value= 1 );

UPDATE EventChoices
SET EventPromotion = 'PROMOTION_HEREDITARYRULE', Expires = 1
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_PATRONAGE', Expires = 1
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_SUFFRAGE', Expires = 1
WHERE Type = 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_NATIONHOOD', Expires = 1
WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5';

UPDATE EventChoices
SET EventBuildingClassGlobal = 'BUILDINGCLASS_CONSTUTIONALISM', Expires = 1
WHERE Type = 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7';

UPDATE EventChoices
SET RequiredAnywhereBuildingClass = 'BUILDINGCLASS_FOUNDERBUILDING'
WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2';

UPDATE EventChoices
SET EventPromotion = 'PROMOTION_DEUSVULT', Expires = 1
WHERE Type = 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3';

INSERT INTO EventChoiceFlavors (EventChoiceType, FlavorType, Flavor)
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'FLAVOR_GOLD', 12 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 8 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_WONDER', 8 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_2', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'FLAVOR_GOLD', 19 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_7', 'FLAVOR_HAPPINESS', -8 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'FLAVOR_DIPLOMACY', 19 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'FLAVOR_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'FLAVOR_PRODUCTION', 1 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_CULTURE', 7 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_RELIGION', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_GREAT_PEOPLE', 8 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_PRODUCTION', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_4', 'FLAVOR_GROWTH', 2 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_GOLD', 4 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_HAPPINESS', 15 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_OFFENSE', 12 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_DEFENSE', 12 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_MILITARY_TRAINING', 8 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_CITY_DEFENSE', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_5', 'FLAVOR_ESPIONAGE', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_GOLD', 5 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_PRODUCTION', 15 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 4 UNION ALL
SELECT 'PLAYER_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'FLAVOR_GROWTH', 15 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'FLAVOR_GOLD', 12 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 8 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_GREAT_PEOPLE', 6 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_GROWTH', 8 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_EXPANSION', 4 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_2', 'FLAVOR_GOLD', 12 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_MILITARY_TRAINING', 15 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_OFFENSE', 8 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_DEFENSE', 8 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_3', 'FLAVOR_GOLD', 4 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_GOLD', 5 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_PRODUCTION', 8 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_WONDER', 8 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_4', 'FLAVOR_HAPPINESS', 12 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'FLAVOR_GOLD', 12 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'FLAVOR_ESPIONAGE', 23 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_5', 'FLAVOR_DIPLOMACY', 4 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'FLAVOR_GOLD', 9 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 26 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_GOLD', 4 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_HAPPINESS', 23 UNION ALL
SELECT 'PLAYER_EVENT_LEGALCIVIC_CHOICE_7', 'FLAVOR_CULTURE', 4 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'FLAVOR_GOLD', 12 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 8 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_EXPANSION', 4 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_OFFENSE', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_TILE_IMPROVEMENT', 8 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_PRODUCTION', 12 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_2', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_PRODUCTION', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_GOLD', 20 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_GROWTH', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_TILE_IMPROVEMENT', 20 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_3', 'FLAVOR_EXPANSION', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_GREAT_PEOPLE', 15 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_PRODUCTION', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_CULTURE', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_4', 'FLAVOR_MILITARY_TRAINING', 2 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'FLAVOR_PRODUCTION', 25 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_5', 'FLAVOR_GROWTH', 5 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_PRODUCTION', 12 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_GROWTH', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_SCIENCE', 3 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_7', 'FLAVOR_HAPPINESS', 6 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'FLAVOR_HAPPINESS', 27 UNION ALL
SELECT 'PLAYER_EVENT_LABORCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 4 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'FLAVOR_GOLD', 12 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 8 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'FLAVOR_GOLD', 13 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_7', 'FLAVOR_DIPLOMACY', 2 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_PRODUCTION', 8 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_2', 'FLAVOR_GROWTH', 9 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_GOLD', 10 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_CULTURE', 4 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_TILE_IMPROVEMENT', 1 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_I_LAND_TRADE_ROUTE', 12 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_3', 'FLAVOR_I_SEA_TRADE_ROUTE', 12 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_GROWTH', 23 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_PRODUCTION', 19 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_CULTURE', 12 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_4', 'FLAVOR_TILE_IMPROVEMENT', 8 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_HAPPINESS', 23 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_GOLD', 7 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_PRODUCTION', 19 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_CULTURE', 8 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_5', 'FLAVOR_TILE_IMPROVEMENT', 8 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'FLAVOR_GOLD', 4 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'FLAVOR_CULTURE', 15 UNION ALL
SELECT 'PLAYER_EVENT_ECONOMYCIVIC_CHOICE_6', 'FLAVOR_PRODUCTION', -4 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'FLAVOR_GOLD', 12 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_1', 'FLAVOR_HAPPINESS', 8 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'FLAVOR_EXPANSION', 4 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_7', 'FLAVOR_RELIGION', 12 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'FLAVOR_PRODUCTION', 12 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'FLAVOR_RELIGION', 19 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_2', 'FLAVOR_GOLD', 4 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_OFFENSE', 12 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_DEFENSE', 12 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_MILITARY_TRAINING', 4 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_RELIGION', 19 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_3', 'FLAVOR_GOLD', 9 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_CULTURE', 3 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_OFFENSE', -15 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_GREAT_PEOPLE', 30 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_4', 'FLAVOR_RELIGION', 8 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_CULTURE', 23 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_HAPPINESS', 5 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_5', 'FLAVOR_RELIGION', 8 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_GOLD', 8 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_SCIENCE', 23 UNION ALL
SELECT 'PLAYER_EVENT_RELIGIONCIVIC_CHOICE_6', 'FLAVOR_HAPPINESS', 15;

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
SELECT 'BUILDINGCLASS_TAX', 'BUILDING_TAXTAXTAX', 'TXT_KEY_TAX' UNION ALL
SELECT 'BUILDINGCLASS_CONSTUTIONALISM', 'BUILDING_CONSTUTIONALISM', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7' UNION ALL
SELECT 'BUILDINGCLASS_PATRONAGE', 'BUILDING_PATRONAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3' UNION ALL
SELECT 'BUILDINGCLASS_INGENIUS_CRAFT', 'BUILDING_INGENIUS_CRAFT', 'TXT_KEY_EVENT_ECONOMYCIVIC_CHOICE_7' UNION ALL
SELECT 'BUILDINGCLASS_ANCESTOR_WORSHIP', 'BUILDING_ANCESTOR_WORSHIP', 'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION' UNION ALL
SELECT 'BUILDINGCLASS_NATIONHOOD', 'BUILDING_NATIONHOOD', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5' UNION ALL
SELECT 'BUILDINGCLASS_STATE_ATHEISM', 'BUILDING_STATE_ATHEISM', 'TXT_KEY_STATE_ATHEISM_DESCRIPTION' UNION ALL
SELECT 'BUILDINGCLASS_SUFFRAGE', 'BUILDING_SUFFRAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6' UNION All
SELECT 'BUILDINGCLASS_FOUNDERBUILDING', 'BUILDING_FOUNDERBUILDING', 'TXT_KEY_MAINTENANCEBUILDING';

INSERT INTO Buildings (Type, Description, BuildingClass, Cost, PrereqTech, ArtDefineTag, MinAreaSize, NeverCapture, NukeImmune, HurryCostModifier, PortraitIndex, IconAtlas, GreatWorkCount, FaithCost, ReligiousPressureModifier, IsDummy)
SELECT 'BUILDING_TAXTAXTAX', 'TXT_KEY_TAX', 'BUILDINGCLASS_TAX', -1, NULL, 'NONE', -1, 'false', 'true', -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
SELECT 'BUILDING_CONSTUTIONALISM', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_7', 'BUILDINGCLASS_CONSTUTIONALISM', -1, NULL, 'NONE', -1, 'true', 'true', -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
SELECT 'BUILDING_PATRONAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_3', 'BUILDINGCLASS_PATRONAGE', -1, NULL, 'NONE', -1, 'true', 'true', -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
SELECT 'BUILDING_ANCESTOR_WORSHIP', 'TXT_KEY_ANCESTOR_WORSHIP_DESCRIPTION', 'BUILDINGCLASS_ANCESTOR_WORSHIP', -1, NULL, 'NONE', -1, 'true', 'true', -1, 4, 'MORE_SPECIALIST_ATLAS', 0, 75, 0, 0 UNION ALL
SELECT 'BUILDING_NATIONHOOD', 'TXT_KEY_EVENT_LEGALCIVIC_CHOICE_5', 'BUILDINGCLASS_NATIONHOOD', -1, NULL, 'NONE', -1, 'true', 'true', -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION All
SELECT 'BUILDING_STATE_ATHEISM', 'TXT_KEY_STATE_ATHEISM_DESCRIPTION', 'BUILDINGCLASS_STATE_ATHEISM', 1800, NULL, 'NONE', -1, 'true', 'true', -1, 5, 'MORE_SPECIALIST_ATLAS', 0, 0, 0, 0 UNION ALL
SELECT 'BUILDING_SUFFRAGE', 'TXT_KEY_EVENT_GOVERNMENTCIVIC_CHOICE_6', 'BUILDINGCLASS_SUFFRAGE', -1, NULL, 'NONE', -1, 'true', 'true', -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1 UNION ALL
SELECT 'BUILDING_FOUNDERBUILDING', 'TXT_KEY_MAINTENANCEBUILDING', 'BUILDINGCLASS_FOUNDERBUILDING', -1, NULL, 'NONE', -1, 'false', 'true', -1, 0, 'CIV_COLOR_ATLAS', -1, -1, 0, 1;

UPDATE Buildings SET FreeBuildingThisCity = 'BUILDINGCLASS_FOUNDERBUILDING' WHERE BuildingClass = 'BUILDINGCLASS_MAUSOLEUM';
UPDATE Buildings SET FreeBuildingThisCity = 'BUILDINGCLASS_FOUNDERBUILDING' WHERE BuildingClass = 'BUILDINGCLASS_HEAVENLY_THRONE';
UPDATE Buildings SET FreeBuildingThisCity = 'BUILDINGCLASS_FOUNDERBUILDING' WHERE BuildingClass = 'BUILDINGCLASS_GREAT_ALTAR';
UPDATE Buildings SET FreeBuildingThisCity = 'BUILDINGCLASS_FOUNDERBUILDING' WHERE BuildingClass = 'BUILDINGCLASS_RELIQUARY';
UPDATE Buildings SET FreeBuildingThisCity = 'BUILDINGCLASS_FOUNDERBUILDING' WHERE BuildingClass = 'BUILDINGCLASS_DIVINE_COURT';
UPDATE Buildings SET FreeBuildingThisCity = 'BUILDINGCLASS_FOUNDERBUILDING' WHERE BuildingClass = 'BUILDINGCLASS_SACRED_GARDEN';
UPDATE Buildings SET FreeBuildingThisCity = 'BUILDINGCLASS_FOUNDERBUILDING' WHERE BuildingClass = 'BUILDINGCLASS_HOLY_COUNCIL';
UPDATE Buildings SET FreeBuildingThisCity = 'BUILDINGCLASS_FOUNDERBUILDING' WHERE BuildingClass = 'BUILDINGCLASS_APOSTOLIC_PALACE';
UPDATE Buildings SET FreeBuildingThisCity = 'BUILDINGCLASS_FOUNDERBUILDING' WHERE BuildingClass = 'BUILDINGCLASS_GRAND_OSSUARY';

UPDATE Buildings
SET ConquestProb = 100
WHERE Type = 'BUILDING_TAXTAXTAX';

UPDATE Buildings
SET ConquestProb = 100
WHERE Type = 'BUILDING_FOUNDERBUILDING';

UPDATE Buildings
SET PolicyType = 'POLICY_CIVIC_ANCESTOR_WORSHIP'
WHERE Type = 'BUILDING_ANCESTOR_WORSHIP';

UPDATE Buildings
SET PolicyType = 'POLICY_CIVIC_STATE_ATHEISM', GoldMaintenance = 1
WHERE Type = 'BUILDING_STATE_ATHEISM';

INSERT INTO Building_YieldFromSpyDefense (BuildingType, YieldType, Yield)
SELECT 'BUILDING_NATIONHOOD', 'YIELD_GOLDEN_AGE_POINTS', 200 UNION ALL
SELECT 'BUILDING_NATIONHOOD', 'YIELD_GOLD', 200;

INSERT INTO Building_YieldPerFriend (BuildingType, YieldType, Yield)
SELECT 'BUILDING_PATRONAGE', 'YIELD_GOLD', 1;

INSERT INTO Building_YieldPerAlly (BuildingType, YieldType, Yield)
SELECT 'BUILDING_PATRONAGE', 'YIELD_TOURISM', 1;

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_SUFFRAGE', 'YIELD_FOOD', 33 UNION ALL
SELECT 'BUILDING_SUFFRAGE', 'YIELD_PRODUCTION', 33 UNION ALL
SELECT 'BUILDING_SUFFRAGE', 'YIELD_GOLD', 33 UNION ALL
SELECT 'BUILDING_CONSTUTIONALISM', 'YIELD_GOLDEN_AGE_POINTS', 100;

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ANCESTOR_WORSHIP', 'YIELD_FAITH', 1 UNION ALL
SELECT 'BUILDING_ANCESTOR_WORSHIP', 'YIELD_CULTURE_LOCAL', 1 UNION ALL
SELECT 'BUILDING_STATE_ATHEISM', 'YIELD_CULTURE', 1;

INSERT INTO UnitPromotions (Type, Description, Help, Sound, CannotBeChosen, PortraitIndex, IconAtlas, PediaType, PediaEntry)
SELECT 'PROMOTION_DEUSVULT', 'TXT_KEY_PROMOTION_DEUSVULT', 'TXT_KEY_PROMOTION_DEUSVULT_HELP', 'AS2D_IF_LEVELUP', 1, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DEUSVULT' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'TXT_KEY_PROMOTION_HEREDITARYRULE', 'TXT_KEY_PROMOTION_HEREDITARYRULE_HELP', 'AS2D_IF_LEVELUP', 1, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DEUSVULT';

UPDATE UnitPromotions
SET FriendlyHealChange = 5, NeutralHealChange = 5
WHERE Type = 'PROMOTION_DEUSVULT';

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_DEUSVULT', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'UNITCOMBAT_ARMOR';

INSERT INTO UnitPromotions_YieldChanges (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_HEREDITARYRULE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PROMOTION_HEREDITARYRULE', 'YIELD_PRODUCTION', 1;