/*
What is this? If you have More Luxury, then the mod itself will automatically 
*/
INSERT INTO Building_ResourceYieldChanges (BuildingType, ResourceType, YieldType, Yield)
SELECT 'BUILDING_MARA', 'RESOURCE_AMBER' , 'YIELD_CULTURE' , 1 WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_AMBER') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MOAI' AND Value= 1) UNION ALL
SELECT 'BUILDING_MARA', 'RESOURCE_AMBER' , 'YIELD_FAITH' , 1 WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_AMBER') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MOAI' AND Value= 1) UNION ALL
SELECT 'BUILDING_STEMPLES', 'RESOURCE_AMBER' , 'YIELD_GOLD' , 1 WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_AMBER') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_TERRACE_FARM' AND Value= 1 ) UNION ALL
SELECT 'BUILDING_STEMPLES', 'RESOURCE_AMBER' , 'YIELD_CULTURE' , 1 WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_AMBER') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_TERRACE_FARM' AND Value= 1 ) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_AMBER' , 'YIELD_SCIENCE' , 1 WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_AMBER') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_JADE' , 'YIELD_SCIENCE' , 1 WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_JADE') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_LAPIS' , 'YIELD_SCIENCE' , 1 WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_LAPIS') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_LocalResourceOrs (BuildingType, ResourceType)
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_JADE' WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_JADE') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_AMBER' WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_AMBER') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_LAPIS' WHERE EXISTS (SELECT * FROM Resources WHERE Type='RESOURCE_LAPIS') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

-- Don't touch this. --
UPDATE Buildings
SET HurryCostModifier = '5'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

UPDATE Buildings
SET HurryCostModifier = '-5'
WHERE NOT WonderSplashImage = 'NULL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );