INSERT INTO LocalizedText (Language, Tag, Text)
	SELECT 'en_US', 'TXT_KEY_BUILDING_MONUMENT_UP_MIGHT', 'Monument of Authority' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_MONUMENT_UP_MIGHT_STRATEGY', 'Reduce [ICON_HAPPINESS_3] Distress marginally.[NEWLINE][NEWLINE]+1 [ICON_GOLD] Gold to Barrack and Armory.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_MONUMENT_UP_LABOR', 'Monument of Prosperity' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_MONUMENT_UP_LABOR_STRATEGY', '+1 [ICON_FOOD] Food or +1 [ICON_PRODUCTION] to Well or Watermill.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_SHRINE_UP_MIGHT', 'Shrine of Strength' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_SHRINE_UP_MIGHT_STRATEGY', 'Reduce [ICON_HAPPINESS_3] Distress marginally.[NEWLINE][NEWLINE]+1 [ICON_PEACE] Faith to Cathedral, Order, and Monastery.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_SHRINE_UP_LABOR', 'Shrine of Nourishment' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_SHRINE_UP_LABOR_STRATEGY', '+1 [ICON_PEACE] Faith to Synagogue, Mandir, and Monastery.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_TEMPLE_UP_MIGHT', 'Temple of Power' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_TEMPLE_UP_MIGHT_STRATEGY', 'Reduce [ICON_HAPPINESS_3] Distress marginally.[NEWLINE][NEWLINE]+2 [ICON_GOLD] Gold to Holy Sites. +1 [ICON_PEACE] Faith to Forts and Citadels.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_TEMPLE_UP_LABOR', 'Temple of Sustainment' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_TEMPLE_UP_LABOR_STRATEGY', '+2 [ICON_PRODUCTION] Production and +2 [ICON_FOOD] Food to Holy Sites.'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Buildings (Type, BuildingClass, Cost, GoldMaintenance, Help, Description, Civilopedia, Strategy, ArtDefineTag, MinAreaSize, MutuallyExclusiveGroup, AllowsRangeStrike, DefenseHappinessChange, IconAtlas, NeverCapture, PortraitIndex, HurryCostModifier)
	SELECT 'BUILDING_MONUMENT_UP_MIGHT', 'BUILDINGCLASS_MONUMENT_UP_MIGHT', 60, 0, 'TXT_KEY_BUILDING_MONUMENT_UP_MIGHT_STRATEGY', 'TXT_KEY_BUILDING_MONUMENT_UP_MIGHT', 'TXT_KEY_BUILDING_MONUMENT_PEDIA', 'TXT_KEY_BUILDING_MONUMENT_UP_MIGHT_STRATEGY', 'MONUMENT', -1, 18, 1, -3, 'BW_ATLAS_1', 1, 21, 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_LABOR', 'BUILDINGCLASS_MONUMENT_UP_LABOR', 60, 0, 'TXT_KEY_BUILDING_MONUMENT_UP_LABOR_STRATEGY', 'TXT_KEY_BUILDING_MONUMENT_UP_LABOR', 'TXT_KEY_BUILDING_MONUMENT_PEDIA', 'TXT_KEY_BUILDING_MONUMENT_UP_LABOR_STRATEGY', 'MONUMENT', -1, 18, NULL, NULL, 'BW_ATLAS_1', 1, 21, 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_MIGHT', 'BUILDINGCLASS_SHRINE_UP_MIGHT', 60, 0, 'TXT_KEY_BUILDING_SHRINE_UP_MIGHT_STRATEGY', 'TXT_KEY_BUILDING_SHRINE_UP_MIGHT', 'TXT_KEY_CIV5_BUILDINGS_SHRINE_TEXT', 'TXT_KEY_BUILDING_SHRINE_UP_MIGHT_STRATEGY', 'TEMPLE', -1, 19, 1, -3, 'EXPANSION_BW_ATLAS_1', 1, 9, 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_LABOR', 'BUILDINGCLASS_SHRINE_UP_LABOR', 60, 0, 'TXT_KEY_BUILDING_SHRINE_UP_LABOR_STRATEGY', 'TXT_KEY_BUILDING_SHRINE_UP_LABOR', 'TXT_KEY_CIV5_BUILDINGS_SHRINE_TEXT', 'TXT_KEY_BUILDING_SHRINE_UP_LABOR_STRATEGY', 'TEMPLE', -1, 19, NULL, NULL, 'EXPANSION_BW_ATLAS_1', 1, 9, 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_MIGHT', 'BUILDINGCLASS_TEMPLE_UP_MIGHT', 90, 0, 'TXT_KEY_BUILDING_TEMPLE_UP_MIGHT_STRATEGY', 'TXT_KEY_BUILDING_TEMPLE_UP_MIGHT', 'TXT_KEY_CIV5_BUILDINGS_TEMPLE_TEXT', 'TXT_KEY_BUILDING_TEMPLE_UP_MIGHT_STRATEGY', 'TEMPLE', -1, 20, NULL, -4, 'BW_ATLAS_1', 1, 37, 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_LABOR', 'BUILDINGCLASS_TEMPLE_UP_LABOR', 90, 0, 'TXT_KEY_BUILDING_TEMPLE_UP_LABOR_STRATEGY', 'TXT_KEY_BUILDING_TEMPLE_UP_LABOR', 'TXT_KEY_CIV5_BUILDINGS_TEMPLE_TEXT', 'TXT_KEY_BUILDING_TEMPLE_UP_LABOR_STRATEGY', 'TEMPLE', -1, 20, NULL, NULL, 'BW_ATLAS_1', 1, 37, 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
	SELECT 'BUILDINGCLASS_MONUMENT_UP_MIGHT', 'BUILDING_MONUMENT_UP_MIGHT', 'TXT_KEY_BUILDING_MONUMENT_UP_MIGHT' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_MONUMENT_UP_LABOR', 'BUILDING_MONUMENT_UP_LABOR', 'TXT_KEY_BUILDING_MONUMENT_UP_LABOR' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_SHRINE_UP_MIGHT', 'BUILDING_SHRINE_UP_MIGHT', 'TXT_KEY_BUILDING_SHRINE_UP_MIGHT' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_SHRINE_UP_LABOR', 'BUILDING_SHRINE_UP_LABOR', 'TXT_KEY_BUILDING_SHRINE_UP_LABOR' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_TEMPLE_UP_MIGHT', 'BUILDING_TEMPLE_UP_MIGHT', 'TXT_KEY_BUILDING_TEMPLE_UP_MIGHT' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_TEMPLE_UP_LABOR', 'BUILDING_TEMPLE_UP_LABOR', 'TXT_KEY_BUILDING_TEMPLE_UP_LABOR' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_DomainFreeExperiences (BuildingType, DomainType, Experience)
	SELECT 'BUILDING_MONUMENT_UP_MIGHT', 'DOMAIN_LAND', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_MIGHT', 'DOMAIN_SEA', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_MIGHT', 'DOMAIN_LAND', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_MIGHT', 'DOMAIN_SEA', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_MIGHT', 'DOMAIN_LAND', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_MIGHT', 'DOMAIN_SEA', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
	SELECT 'BUILDING_MONUMENT_UP_MIGHT', 'FLAVOR_MILITARY_TRAINING', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_LABOR', 'FLAVOR_PRODUCTION', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_MIGHT', 'FLAVOR_MILITARY_TRAINING', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_LABOR', 'FLAVOR_PRODUCTION', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_MIGHT', 'FLAVOR_MILITARY_TRAINING', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_LABOR', 'FLAVOR_PRODUCTION', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
	SELECT 'BUILDING_MONUMENT_UP_MIGHT', 'BUILDINGCLASS_MONUMENT' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_LABOR', 'BUILDINGCLASS_MONUMENT' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_MIGHT', 'BUILDINGCLASS_SHRINE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_LABOR', 'BUILDINGCLASS_SHRINE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_MIGHT', 'BUILDINGCLASS_TEMPLE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_LABOR', 'BUILDINGCLASS_TEMPLE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_MONUMENT_UP_LABOR', 'YIELD_PRODUCTION', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_LABOR', 'YIELD_FOOD', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_MIGHT', 'YIELD_GOLDEN_AGE_POINTS', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_LABOR', 'YIELD_PRODUCTION', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_LABOR', 'YIELD_FOOD', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_MIGHT', 'YIELD_GOLDEN_AGE_POINTS', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_LABOR', 'YIELD_PRODUCTION', 3 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_LABOR', 'YIELD_FOOD', 3 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP', 'YIELD_CULTURE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_MIGHT', 'YIELD_GOLDEN_AGE_POINTS', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_ImprovementYieldChanges (BuildingType, ImprovementType, YieldType, Yield)
	SELECT 'BUILDING_TEMPLE_UP_LABOR', 'IMPROVEMENT_HOLY_SITE', 'YIELD_PRODUCTION', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_LABOR', 'IMPROVEMENT_HOLY_SITE', 'YIELD_FOOD', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP', 'IMPROVEMENT_HOLY_SITE', 'YIELD_CULTURE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP', 'IMPROVEMENT_HOLY_SITE', 'YIELD_FAITH', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_MIGHT', 'IMPROVEMENT_CITADEL', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_MIGHT', 'IMPROVEMENT_FORT', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_TEMPLE_UP_MIGHT', 'IMPROVEMENT_HOLY_SITE', 'YIELD_GOLD', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_BuildingClassLocalYieldChanges (BuildingType, BuildingClassType, YieldType, YieldChange)
	SELECT 'BUILDING_SHRINE_UP', 'BUILDINGCLASS_STUPA', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP', 'BUILDINGCLASS_PAGODA', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP', 'BUILDINGCLASS_MONASTERY', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_MIGHT', 'BUILDINGCLASS_ORDER', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_MIGHT', 'BUILDINGCLASS_CATHEDRAL', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_MIGHT', 'BUILDINGCLASS_MONASTERY', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_LABOR', 'BUILDINGCLASS_MANDIR', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_LABOR', 'BUILDINGCLASS_SYNAGOGUE', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_SHRINE_UP_LABOR', 'BUILDINGCLASS_MONASTERY', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP', 'BUILDINGCLASS_AMPHITHEATER', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP', 'BUILDINGCLASS_TEMPLE', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_LABOR', 'BUILDINGCLASS_WELL', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_LABOR', 'BUILDINGCLASS_WATERMILL', 'YIELD_PRODUCTION', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_MIGHT', 'BUILDINGCLASS_ARMORY', 'YIELD_GOLD', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MONUMENT_UP_MIGHT', 'BUILDINGCLASS_BARRACKS', 'YIELD_GOLD', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);