INSERT INTO LocalizedText (Language, Tag, Text)
	SELECT 'en_US', 'TXT_KEY_BUILDING_CARAVANSARY_UP', 'Flea Market' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_CARAVANSARY_UP_STRATEGY', '+1 [ICON_GOLD] Gold for every 10 [ICON_CITIZEN] Population. +2 [ICON_GREAT_MERCHANT] Great Merchant Points.[NEWLINE][NEWLINE]Receive more [ICON_TOURISM] Tourism from completed [ICON_INTERNATIONAL_TRADE] Land Trade Routes.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_HARBOR_UP', 'Dock' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_HARBOR_UP_STRATEGY', '+1 [ICON_FOOD] Food to Ocean tiles. -1 [ICON_GOLD] Gold for every 2 [ICON_CITIZEN] Population.[NEWLINE][NEWLINE]Receive more [ICON_TOURISM] Tourism from completed [ICON_INTERNATIONAL_TRADE] Sea Trade Routes.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_PUBLIC_SCHOOL_UP', 'Educational Institute' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_PUBLIC_SCHOOL_UP_STRATEGY', '+1 [ICON_RESEARCH] Science for every 6 [ICON_CITIZEN] Population. -1 [ICON_GOLD] Gold for every 3 [ICON_CITIZEN] Population. +1 [ICON_GREAT_PEOPLE] Scientist Slot.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_STOCK_EXCHANGE_UP', 'Finance Company' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_STOCK_EXCHANGE_UP_STRATEGY', '+1 [ICON_GOLD] Gold for every 5 [ICON_CITIZEN] Population and +1 [ICON_GREAT_MERCHANT] Merchant Slot.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_ART', 'Artist Tower' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_ART_STRATEGY', '+1 [ICON_CULTURE] Culture for every 5 [ICON_CITIZEN] Population and +1 [ICON_GREAT_PEOPLE] Artist Slot.' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_WRITE', 'Writer Tower' UNION ALL
	SELECT 'en_US', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_WRITER_STRATEGY', '+1 [ICON_CULTURE] Culture for every 5 [ICON_CITIZEN] Population and +1 [ICON_GREAT_PEOPLE] Writer Slot.'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Buildings (Type, BuildingClass, Cost, GoldMaintenance, PrereqTech, Help, Description, Civilopedia, Strategy, ArtDefineTag, SpecialistType, SpecialistCount, GreatPeopleRateChange, MinAreaSize, HurryCostModifier, MutuallyExclusiveGroup, DisplayPosition, IconAtlas, NeverCapture, PortraitIndex)
	SELECT 'BUILDING_BROADCAST_TOWER_UP_ART', 'BUILDINGCLASS_BROADCAST_TOWER_UP_ART', 500, 6, NULL, 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_ART_STRATEGY', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_ART', 'TXT_KEY_CIV5_BUILDINGS_BROADCASTTOWER_TEXT', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_ART_STRATEGY', 'RADIO TOWER', 'SPECIALIST_ARTIST', 1, 1, -1, 5, 21, 2, 'BW_ATLAS_1', 1, 35 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_BROADCAST_TOWER_UP_WRITE', 'BUILDINGCLASS_BROADCAST_TOWER_UP_WRITE', 500, 6, NULL, 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_WRITER_STRATEGY', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_WRITE', 'TXT_KEY_CIV5_BUILDINGS_BROADCASTTOWER_TEXT', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_WRITER_STRATEGY', 'RADIO TOWER', 'SPECIALIST_WRITER', 1, 1, -1, 5, 21, 2, 'BW_ATLAS_1', 1, 35 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_CARAVANSARY_UP', 'BUILDINGCLASS_CARAVANSARY_UP', 125, 1, NULL, 'TXT_KEY_BUILDING_CARAVANSARY_UP_STRATEGY', 'TXT_KEY_BUILDING_CARAVANSARY_UP', 'TXT_KEY_CIV5_BUILDINGS_CARAVANSARY_TEXT', 'TXT_KEY_BUILDING_CARAVANSARY_UP_STRATEGY', 'ART_DEF_BUILDING_CARAVANSARY', 'SPECIALIST_MERCHANT', 0, 2, -1, 5, -1, NULL, 'EXPANSION2_BUILDING_ATLAS', 1, 8 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_HARBOR_UP', 'BUILDINGCLASS_HARBOR_UP', 150, 1, NULL, 'TXT_KEY_BUILDING_HARBOR_UP_STRATEGY', 'TXT_KEY_BUILDING_HARBOR_UP', 'TXT_KEY_BUILDING_HARBOR_PEDIA', 'TXT_KEY_BUILDING_HARBOR_UP_STRATEGY', 'HARBOR', NULL, NULL, NULL, -1, 5, -1, NULL, 'BW_ATLAS_1', 1, 26 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_PUBLIC_SCHOOL_UP', 'BUILDINGCLASS_PUBLIC_SCHOOL_UP', 475, 6, NULL, 'TXT_KEY_BUILDING_PUBLIC_SCHOOL_UP_STRATEGY', 'TXT_KEY_BUILDING_PUBLIC_SCHOOL_UP', 'TXT_KEY_CIV5_BUILDINGS_PUBLIC_SCHOOL_TEXT', 'TXT_KEY_BUILDING_PUBLIC_SCHOOL_UP_STRATEGY', 'ART_DEF_BUILDING_PUBLIC_SCHOOL', 'SPECIALIST_SCIENTIST', 1, 3, -1, 5, -1, NULL, 'BW_ATLAS_1', 1, 14 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_STOCK_EXCHANGE_UP', 'BUILDINGCLASS_STOCK_EXCHANGE_UP', 500, 9, NULL, 'TXT_KEY_BUILDING_STOCK_EXCHANGE_UP_STRATEGY', 'TXT_KEY_BUILDING_STOCK_EXCHANGE_UP', 'TXT_KEY_CIV5_BUILDINGS_STOCK_EXCHANGE_TEXT', 'TXT_KEY_BUILDING_STOCK_EXCHANGE_UP_STRATEGY', 'ART_DEF_BUILDING_STOCK_EXCHANGE', 'SPECIALIST_MERCHANT', 1, 2, -1, 5, -1, NULL, 'BW_ATLAS_1', 1, 56 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);	

UPDATE Buildings
SET FinishLandTRTourism = 2
WHERE Type = 'BUILDING_CARAVANSARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Buildings
SET FinishSeaTRTourism = 2
WHERE Type = 'BUILDING_HARBOR_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
	SELECT 'BUILDINGCLASS_BROADCAST_TOWER_UP_ART', 'BUILDING_BROADCAST_TOWER_UP_ART', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_ART' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_BROADCAST_TOWER_UP_WRITE', 'BUILDING_BROADCAST_TOWER_UP_WRITE', 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_WRITE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_CARAVANSARY_UP', 'BUILDING_CARAVANSARY_UP', 'TXT_KEY_BUILDING_CARAVANSARY_UP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_HARBOR_UP', 'BUILDING_HARBOR_UP', 'TXT_KEY_BUILDING_HARBOR_UP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_PUBLIC_SCHOOL_UP', 'BUILDING_PUBLIC_SCHOOL_UP', 'TXT_KEY_BUILDING_PUBLIC_SCHOOL_UP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDINGCLASS_STOCK_EXCHANGE_UP', 'BUILDING_STOCK_EXCHANGE_UP', 'TXT_KEY_BUILDING_STOCK_EXCHANGE_UP' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_SeaPlotYieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_HARBOR_UP', 'YIELD_FOOD', 1
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_Flavors(BuildingType, FlavorType, Flavor)
	SELECT 'BUILDING_CARAVANSARY_UP', 'FLAVOR_GOLD', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_CARAVANSARY_UP', 'FLAVOR_GREAT_PEOPLE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_CARAVANSARY_UP', 'FLAVOR_I_LAND_TRADE_ROUTE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_HARBOR_UP', 'FLAVOR_NAVAL_GROWTH', 25 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_HARBOR_UP', 'FLAVOR_GROWTH', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_HARBOR_UP', 'FLAVOR_I_SEA_TRADE_ROUTE', 5 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_PUBLIC_SCHOOL_UP', 'FLAVOR_SCIENCE', 17 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_STOCK_EXCHANGE_UP', 'FLAVOR_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_STOCK_EXCHANGE_UP', 'FLAVOR_GREAT_PEOPLE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_BROADCAST_TOWER_UP_ART', 'FLAVOR_CULTURE', 50 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_BROADCAST_TOWER_UP_WRITE', 'FLAVOR_CULTURE', 50 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
	SELECT 'BUILDING_CARAVANSARY_UP', 'BUILDINGCLASS_CARAVANSARY' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_HARBOR_UP', 'BUILDINGCLASS_HARBOR' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_PUBLIC_SCHOOL_UP', 'BUILDINGCLASS_PUBLIC_SCHOOL' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_STOCK_EXCHANGE_UP', 'BUILDINGCLASS_STOCK_EXCHANGE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_BROADCAST_TOWER_UP_ART', 'BUILDINGCLASS_BROADCAST_TOWER' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_BROADCAST_TOWER_UP_WRITE', 'BUILDINGCLASS_BROADCAST_TOWER' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_CARAVANSARY_UP', 'YIELD_GOLD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_HARBOR_UP', 'YIELD_GOLD', -50 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_PUBLIC_SCHOOL_UP', 'YIELD_SCIENCE', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_PUBLIC_SCHOOL_UP', 'YIELD_GOLD', -33 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_STOCK_EXCHANGE_UP', 'YIELD_GOLD', 20 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_BROADCAST_TOWER_UP_ART', 'YIELD_CULTURE', 20 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_BROADCAST_TOWER_UP_WRITE', 'YIELD_CULTURE', 20 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);