UPDATE Language_en_US
SET Text = 'Monument of Society'
WHERE Tag = 'TXT_KEY_BUILDING_MONUMENT_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_CULTURE] Culture to Temple. +1 [ICON_PEACE] Faith to Amphitheater.'
WHERE Tag = 'TXT_KEY_BUILDING_MONUMENT_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Auditorium'
WHERE Tag = 'TXT_KEY_BUILDING_AMPHITHEATER_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_CULTURE] Culture for every 10 [ICON_CITIZEN] Population and +2 [ICON_GREAT_WRITER] Great Writer Points.'
WHERE Tag = 'TXT_KEY_BUILDING_AMPHITHEATER_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Music Hall'
WHERE Tag = 'TXT_KEY_BUILDING_OPERA_HOUSE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_CULTURE] Culture for every 8 [ICON_CITIZEN] Population and +2 [ICON_GREAT_MUSICIAN] Great Musician Points.'
WHERE Tag = 'TXT_KEY_BUILDING_OPERA_HOUSE_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Art Exhibition'
WHERE Tag = 'TXT_KEY_BUILDING_MUSEUM_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_CULTURE] Culture for every 6 [ICON_CITIZEN] Population and +2 [ICON_GREAT_ARTIST] Great Artist Points.'
WHERE Tag = 'TXT_KEY_BUILDING_MUSEUM_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Music Tower'
WHERE Tag = 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_CULTURE] Culture for every 5 [ICON_CITIZEN] Population and +1 [ICON_GREAT_PEOPLE] Musician Slot.'
WHERE Tag = 'TXT_KEY_BUILDING_BROADCAST_TOWER_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_GRANARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_GRANARY_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

UPDATE Language_en_US
SET Text = 'Watercourse'
WHERE Tag = 'TXT_KEY_BUILDING_AQUEDUCT_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+20% of the [ICON_FOOD] Food of the City is added to the current [ICON_FOOD] Food total every time the city gains a [ICON_CITIZEN] Citizen.[NEWLINE][NEWLINE]+1 [ICON_FOOD] for every 10 [ICON_CITIZEN] Population.'
WHERE Tag = 'TXT_KEY_BUILDING_AQUEDUCT_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Infirmary'
WHERE Tag = 'TXT_KEY_BUILDING_HOSPITAL_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_FOOD] Food for every 5 [ICON_CITIZEN] Population.'
WHERE Tag = 'TXT_KEY_BUILDING_HOSPITAL_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_BARRACKS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_BARRACKS_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

UPDATE Language_en_US
SET Text = 'Arms Depot'
WHERE Tag = 'TXT_KEY_BUILDING_ARMORY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+15 XP for all Units. +1 [ICON_RESEARCH] Science.'
WHERE Tag = 'TXT_KEY_BUILDING_ARMORY_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Service Academy'
WHERE Tag = 'TXT_KEY_BUILDING_MILITARY_ACADEMY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+20 XP for all Units. +2 [ICON_RESEARCH] Science.'
WHERE Tag = 'TXT_KEY_BUILDING_MILITARY_ACADEMY_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Fortress'
WHERE Tag = 'TXT_KEY_BUILDING_CASTLE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_WALLS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_WALLS_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

UPDATE Language_en_US
SET Text = 'Extends the distance of land and naval trade routes by 30% and 15% respectively.'
WHERE Tag = 'TXT_KEY_BUILDING_CASTLE_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_ARSENAL_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_ARSENAL_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

UPDATE Language_en_US
SET Text = 'Military Camp'
WHERE Tag = 'TXT_KEY_BUILDING_MILITARY_BASE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Extends the distance of land and naval trade routes distance by 70% and 35% respectively.'
WHERE Tag = 'TXT_KEY_BUILDING_MILITARY_BASE_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_LIBRARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_LIBRARY_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

UPDATE Language_en_US
SET Text = 'Instruction Center'
WHERE Tag = 'TXT_KEY_BUILDING_UNIVERSITY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+50% of the [ICON_RESEARCH] Research of the City is added to the current [ICON_RESEARCH] Research total every time the city gains a [ICON_CITIZEN] Citizen.[NEWLINE][NEWLINE]+1 [ICON_RESEARCH] Science for every 10 [ICON_CITIZEN] Population.[NEWLINE]-1 [ICON_GOLD] for every 5 [ICON_CITIZEN] Population.'
WHERE Tag = 'TXT_KEY_BUILDING_UNIVERSITY_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_WORKSHOP_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Language_en_US WHERE Tag = 'TXT_KEY_BUILDING_WORKSHOP_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

UPDATE Language_en_US
SET Text = 'Temple of Doctrine'
WHERE Tag = 'TXT_KEY_BUILDING_TEMPLE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+2 [ICON_PEACE] Faith and [ICON_CULTURE] Culture to Holy Sites.'
WHERE Tag = 'TXT_KEY_BUILDING_TEMPLE_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Shrine of Prestige'
WHERE Tag = 'TXT_KEY_BUILDING_SHRINE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_PEACE] Faith to Stupa, Pagoda, and Monastery.'
WHERE Tag = 'TXT_KEY_BUILDING_SHRINE_UP_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Buildings 
SET SpecialistType = 'SPECIALIST_WRITER', SpecialistCount = 0, GreatPeopleRateChange = 2, GoldMaintenance = 1, HurryCostModifier = 5
WHERE Type = 'BUILDING_AMPHITHEATER_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Buildings 
SET SpecialistType = 'SPECIALIST_MUSICIAN', SpecialistCount = 0, GreatPeopleRateChange = 2, GoldMaintenance = 2, HurryCostModifier = 5
WHERE Type = 'BUILDING_OPERA_HOUSE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Buildings 
SET SpecialistType = 'SPECIALIST_ARTIST', SpecialistCount = 0, GreatPeopleRateChange = 2, GoldMaintenance = 3, HurryCostModifier = 5
WHERE Type = 'BUILDING_MUSEUM_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Buildings
SET MutuallyExclusiveGroup = 21, GreatPeopleRateChange = 1, CultureRateModifier = 0, SpecialistCount = 1, SpecialistType = 'SPECIALIST_MUSICIAN', GoldMaintenance = 6, HurryCostModifier = 5
WHERE Type = 'BUILDING_BROADCAST_TOWER_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Buildings WHERE Type = 'BUILDING_GRANARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From BuildingClasses WHERE Type = 'BUILDINGCLASS_GRANARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_Flavors WHERE BuildingType = 'BUILDING_GRANARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_GRANARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_YieldChanges WHERE BuildingType = 'BUILDING_GRANARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

UPDATE Buildings
SET FoodKept = 0, GoldMaintenance = 1, HurryCostModifier = 5
WHERE Type = 'BUILDING_AQUEDUCT_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_GrowthExtraYield (BuildingType, YieldType, Yield)
SELECT 'BUILDING_AQUEDUCT_UP', 'YIELD_FOOD', 20 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
SELECT 'BUILDING_UNIVERSITY_UP', 'YIELD_SCIENCE', 50 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Buildings
SET GoldMaintenance = 3, Cost = 425, HurryCostModifier = 5
WHERE Type = 'BUILDING_HOSPITAL_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Buildings WHERE Type = 'BUILDING_WALLS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From BuildingClasses WHERE Type = 'BUILDINGCLASS_WALLS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_Flavors WHERE BuildingType = 'BUILDING_WALLS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_WALLS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

UPDATE Buildings
SET TradeRouteLandDistanceModifier = 30, TradeRouteSeaDistanceModifier = 15, Defense = 500, ExtraCityHitPoints = 35, GoldMaintenance = 3, HurryCostModifier = 5
WHERE Type = 'BUILDING_CASTLE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Buildings WHERE Type = 'BUILDING_ARSENAL_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From BuildingClasses WHERE Type = 'BUILDINGCLASS_ARSENAL_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_Flavors WHERE BuildingType = 'BUILDING_ARSENAL_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_ARSENAL_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );


UPDATE Buildings
SET TradeRouteLandDistanceModifier = 70, TradeRouteSeaDistanceModifier = 30, Defense = 900, ExtraCityHitPoints = 65, GoldMaintenance = 5, HurryCostModifier = 5
WHERE Type = 'BUILDING_MILITARY_BASE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Buildings
SET MutuallyExclusiveGroup = 18, FreeStartEra = NULL, Cost = 60, GoldMaintenance = 0, HurryCostModifier = 5
WHERE Type = 'BUILDING_MONUMENT_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Buildings
SET MutuallyExclusiveGroup = 19, GoldMaintenance = 0, Cost = 60, FreeStartEra = NULL, HurryCostModifier = 5
WHERE Type = 'BUILDING_SHRINE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Buildings
SET MutuallyExclusiveGroup = 20, FreeStartEra = NULL, GoldMaintenance = 0
WHERE Type = 'BUILDING_TEMPLE_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Buildings WHERE Type = 'BUILDING_LIBRARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From BuildingClasses WHERE Type = 'BUILDINGCLASS_LIBRARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_Flavors WHERE BuildingType = 'BUILDING_LIBRARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_LIBRARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_YieldModifiers WHERE BuildingType = 'BUILDING_LIBRARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_YieldChangesPerPop WHERE BuildingType = 'BUILDING_LIBRARY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
UPDATE Buildings
SET Cost = 180, NeverCapture = 1, GoldMaintenance = 2, HurryCostModifier = 5
WHERE Type = 'BUILDING_UNIVERSITY_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

DELETE From Buildings WHERE Type = 'BUILDING_WORKSHOP_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From BuildingClasses WHERE Type = 'BUILDINGCLASS_WORKSHOP_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_Flavors WHERE BuildingType = 'BUILDING_WORKSHOP_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_WORKSHOP_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_YieldModifiers WHERE BuildingType = 'BUILDING_WORKSHOP_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

DELETE From Buildings WHERE Type = 'BUILDING_BARRACKS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From BuildingClasses WHERE Type = 'BUILDINGCLASS_BARRACKS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_Flavors WHERE BuildingType = 'BUILDING_BARRACKS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_ClassesNeededInCity WHERE BuildingType = 'BUILDING_BARRACKS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );
DELETE From Building_DomainFreeExperiences WHERE BuildingType = 'BUILDING_BARRACKS_UP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1 );

UPDATE Building_YieldChanges
SET Yield = 2
WHERE BuildingType = 'BUILDING_TEMPLE_UP' AND YieldType = 'YIELD_FAITH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_YieldModifiers
SET Yield = 0
WHERE BuildingType = 'BUILDING_UNIVERSITY_UP' AND YieldType = 'YIELD_SCIENCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_AMPHITHEATER_UP' AND YieldType = 'YIELD_CULTURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_OPERA_HOUSE_UP' AND YieldType = 'YIELD_CULTURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_MUSEUM_UP' AND YieldType = 'YIELD_CULTURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_YieldChanges
SET Yield = 0
WHERE BuildingType = 'BUILDING_BROADCAST_TOWER_UP' AND YieldType = 'YIELD_CULTURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_YieldChanges
SET Yield = 5
WHERE BuildingType = 'BUILDING_HOSPITAL_UP' AND YieldType = 'YIELD_FOOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_DomainFreeExperiences
SET Experience = 15
WHERE BuildingType = 'BUILDING_ARMORY_UP' AND DomainType = 'DOMAIN_LAND' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_DomainFreeExperiences
SET Experience = 15
WHERE BuildingType = 'BUILDING_ARMORY_UP' AND DomainType = 'DOMAIN_SEA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_DomainFreeExperiences
SET Experience = 15
WHERE BuildingType = 'BUILDING_ARMORY_UP' AND DomainType = 'DOMAIN_AIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_DomainFreeExperiences
SET Experience = 20
WHERE BuildingType = 'BUILDING_MILITARY_ACADEMY_UP' AND DomainType = 'DOMAIN_LAND' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_DomainFreeExperiences
SET Experience = 20
WHERE BuildingType = 'BUILDING_MILITARY_ACADEMY_UP' AND DomainType = 'DOMAIN_SEA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

UPDATE Building_DomainFreeExperiences
SET Experience = 20
WHERE BuildingType = 'BUILDING_MILITARY_ACADEMY_UP' AND DomainType = 'DOMAIN_AIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_AQUEDUCT_UP', 'YIELD_FOOD', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_ARMORY_UP', 'YIELD_SCIENCE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MILITARY_ACADEMY_UP', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1);

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
	SELECT 'BUILDING_AQUEDUCT_UP', 'YIELD_FOOD', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_HOSPITAL_UP', 'YIELD_FOOD', 20 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_UNIVERSITY_UP', 'YIELD_SCIENCE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_UNIVERSITY_UP', 'YIELD_GOLD', -20 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_BROADCAST_TOWER_UP', 'YIELD_CULTURE', 20 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_AMPHITHEATER_UP', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_OPERA_HOUSE_UP', 'YIELD_CULTURE', 12 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1) UNION ALL
	SELECT 'BUILDING_MUSEUM_UP', 'YIELD_CULTURE', 15 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_BUS' AND Value= 1); 
